### ISSUE TITLE
qume performance measure

### ISSUE THREAD

**Issue by TaiJuWu** [apache/nuttx#10754]
I want to test my code performance for nuttx.
Is it available test on QEMU?

I attempted use os perf but pipe2 does not work for qemu-armv8a:nsh_smp
Is it resolved? Or I must measure performance on real hardware?

The osperf always trigger memory dump and I don't find any documentation about it.
Can anyone give me some suggestion?

**Comment by xiaoxiang781216** [comment]
> I want to test my code for nuttx. Is it available test on QEMU?
> 

Yes.

> I attempted use os perf but pipe2 does not work for qemu-armv8a:nsh_smp Is it resolved?

what' problem?

> Or I must measure performance on real hardware?
> 

it's always better to meaure on the real hardware.

> The osperf always trigger memory dump and I don't find any documentation about it. Can anyone give me some suggestion?

@Gary-Hobson could you take a look?

**Comment by TaiJuWu** [comment]
> > I want to test my code for nuttx. Is it available test on QEMU?
> 
> Yes.
> 
> > I attempted use os perf but pipe2 does not work for qemu-armv8a:nsh_smp Is it resolved?
> 
> what' problem?
> 
> > Or I must measure performance on real hardware?
> 
> it's always better to meaure on the real hardware.
> 
> > The osperf always trigger memory dump and I don't find any documentation about it. Can anyone give me some suggestion?
> 
> @Gary-Hobson could you take a look?

When I use QEMU to measure performance the time looks incorrect, even only pass 1s on real world but the result shows 14s.

 So I’m not sure this behavior is available.

**Comment by Gary-Hobson** [comment]
> > > I want to test my code for nuttx. Is it available test on QEMU?
> > 
> > 
> > Yes.
> > > I attempted use os perf but pipe2 does not work for qemu-armv8a:nsh_smp Is it resolved?
> > 
> > 
> > what' problem?
> > > Or I must measure performance on real hardware?
> > 
> > 
> > it's always better to meaure on the real hardware.
> > > The osperf always trigger memory dump and I don't find any documentation about it. Can anyone give me some suggestion?
> > 
> > 
> > @Gary-Hobson could you take a look?
> 
> When I use QEMU to measure performance the time looks incorrect, even only pass 1s on real world but the result shows 14s.
> 
> So I’m not sure this behavior is available and I have attempted to find the answer but failed.

There were some issues running on arm64 which I have fixed
I also found that the time you mentioned is incorrect. I am analyzing the reasons now and may have results later.

![image](https://github.com/apache/nuttx/assets/33870028/bfec00be-4ba0-42d3-9a2d-494bbc79cca7)

**Comment by TaiJuWu** [comment]
> > > > I want to test my code for nuttx. Is it available test on QEMU?
> > > 
> > > 
> > > Yes.
> > > > I attempted use os perf but pipe2 does not work for qemu-armv8a:nsh_smp Is it resolved?
> > > 
> > > 
> > > what' problem?
> > > > Or I must measure performance on real hardware?
> > > 
> > > 
> > > it's always better to meaure on the real hardware.
> > > > The osperf always trigger memory dump and I don't find any documentation about it. Can anyone give me some suggestion?
> > > 
> > > 
> > > @Gary-Hobson could you take a look?
> > 
> > 
> > When I use QEMU to measure performance the time looks incorrect, even only pass 1s on real world but the result shows 14s.
> > So I’m not sure this behavior is available and I have attempted to find the answer but failed.
> 
> There were some issues running on arm64 which I have fixed I also found that the time you mentioned is incorrect. I am analyzing the reasons now and may have results later.
> 
> ![image](https://user-images.githubusercontent.com/33870028/269873537-bfec00be-4ba0-42d3-9a2d-494bbc79cca7.png)

Thanks a lot.

**Comment by Gary-Hobson** [comment]
@TaiJuWu You can use this PR(https://github.com/apache/nuttx-apps/pull/2085) to resolve runtime errors.

The time display error is due to the fact that in SMP mode, the time obtained by different CPUs through up_perf_gettime is not synchronized, and end may be smaller than start, resulting in time errors.

![image](https://github.com/apache/nuttx/assets/33870028/5c2adba8-8ba8-4b82-8e87-7a22a7c45a9c)

And you need to enable the following configuration
```
CONFIG_DEBUG_SCHED_INFO=n
CONFIG_PIPES=y
CONFIG_TESTING_OSPERF=y
```
