### ISSUE TITLE
Github README Improvement

### ISSUE THREAD

**Issue by fdcavalcanti** [apache/nuttx#10906]
Hi everyone!

I would like to propose a new README page on Github. The current one is a big wall of text which is already covered in the documentation.
I think we can do something smaller and cleaner just by following some examples online.
Sure, it's a visual thing but I personally think this can help attract more people and gives a "cleaner" look!

Here's what I propose, following these repos as reference: [link 1](https://github.com/zephyrproject-rtos/zephyr), [link 2](https://github.com/pytest-dev/pytest), [link 3](https://github.com/numpy/numpy)

- Put the NuttX logo on top
- Add badges showing status of build, docs, version, etc
- Quick intro to what NuttX is
- Topics on contributing, documentation and getting started

I would love to hear some more ideas from the community, please feel free to add them here.

Filipe

**Comment by acassis** [comment]
I think this is a good suggestion!

**Comment by fdcavalcanti** [comment]
I've created a sample on my fork: [link](https://github.com/fdcavalcanti/nuttx/tree/new-readme)
We can add more badges, improve the logo, wherever is necessary.

**Comment by fdcavalcanti** [comment]
See #10980
