### ISSUE TITLE
Supported Platforms in Documentation

### ISSUE THREAD

**Issue by raiden00pl** [apache/nuttx#10988]
It seems that we have 2 separate places with `Supported Platforms`
One is here  [[1]](https://nuttx.apache.org/docs/latest/introduction/supported_platforms.html) and the other is here:  [[2]](https://nuttx.apache.org/docs/latest/platforms/index.html)

Both pages are incomplete.

[1] has not been updated for a long time and comments regarding the status seem very out of date.
I think we should move from [1] to [2] what is missing and remove [1]

**Comment by TimJTi** [comment]
Not looked at the status details, but 1) is easier to use IMHO. A list of architectures/chips/SOCs with links to page(s) that lists the boards. Isn't that "neater"?

**Comment by raiden00pl** [comment]
> Not looked at the status details, but 1) is easier to use IMHO. A list of architectures/chips/SOCs with links to page(s) that lists the boards. Isn't that "neater"?

I agree that 1 looks better. 
I think [2] is inspired by [Zephyr](https://docs.zephyrproject.org/latest/boards/index.html) and this layout it's not very readable.
But we can deal with visual issues later the outdated list is a bigger problem.

**Comment by raiden00pl** [comment]
closed with https://github.com/apache/nuttx/pull/10991
