### ISSUE TITLE
Buggy handling of unsigned long in vsprintf_internal

### ISSUE THREAD

**Issue by PwnVerse** [apache/nuttx#11155]
When compiling the code on a machine which has unsigned long defined as 8 bytes (64 bit machine), the buggy code [here](https://github.com/apache/nuttx/blob/master/libs/libc/stdio/lib_libvsprintf.c#L414) will mark the second branch as duplicate branch since on 64 bit machines, unsigned long and unsigned long long have the same size, ie, 8 bytes.

```
                  case sizeof(unsigned long):
                    c = 'l';
                    break;

#if defined(CONFIG_HAVE_LONG_LONG) && ULLONG_MAX != ULONG_MAX
                  case sizeof(unsigned long long):
                    c = 'l';
                    flags |= FL_LONG;
                    flags &= ~FL_SHORT;
                    break;
#endif
```

A relatively simple fix would be to have the case for unsigned long in the #else branch of the #if.

```
#if defined(CONFIG_HAVE_LONG_LONG) && ULLONG_MAX != ULONG_MAX
                  case sizeof(unsigned long long):
                    c = 'l';
                    flags |= FL_LONG;
                    flags &= ~FL_SHORT;
                    break;
#else
  case sizeof(unsigned long):
                    c = 'l';
                    break;
#endif
```

This should fix the issue of duplicate branch.

**Comment by acassis** [comment]
@PwnVerse could you please submit a PR with the fix?
If you are new to NuttX I suggested looking here first: https://nuttx.apache.org/docs/latest/contributing/index.html
