### ISSUE TITLE
WIFI thread crash in OTA mode

### ISSUE THREAD

**Issue by dapeng0512** [apache/nuttx#11279]
when i enable OTA with mcuboot in nuttx， the system will crash at ‘esp_wifi_init_internal’ functon，i noticed that this function does not provide source code and cannot analyze specific problems. Does anyone have this problem?

esp-hal-3rdparty version is latest (2fbc8a025275d68833cdfef490377048538de57a) in release/v5.1.c branch

this is full start log.

<img width="1061" alt="image" src="https://github.com/espressif/esp-hal-3rdparty/assets/15180245/dbaa8542-dd3a-4b46-9050-1214399f41b3">

Anyway, Wifi threads in non-OTA mode are not crashing back

Replication step:

1. ./tools/configure.sh esp32s3-devkit:wifi

2. modify config
CONFIG_ESP32S3_HAVE_OTA_PARTTION=y
CONFIG_ESP32S3_STORAGE_MTD_OFFSET=0x250000
CONFIG_ESP32S3_STORAGE_MTD_SIZE=0x100000

others, use default

3. build bootloader and nuttx
4. flash

tks.

**Comment by acassis** [comment]
@tmedicci could you please confirm this issue?

**Comment by tmedicci** [comment]
> @tmedicci could you please confirm this issue?

@eren-terzioglu is investigating it.

**Comment by eren-terzioglu** [comment]
Hi @dapeng0512 

We need to ask some questions and suggestions something to do for understanding your issue correctly and create a solution.

1) First of all, did you compile MCUBoot by yourself or used pre-built one? Did you use `CONFIG_ESP32S3_BOOTLOADER_BUILD_FROM_SOURCE` flag on your custom defconfig file?
2) Could you send nxdiag application output with `nxdiag --all` by using `esp32s3-devkit:nsh` with these options added into [nsh defconfig](https://github.com/apache/nuttx/blob/master/boards/xtensa/esp32s3/esp32s3-devkit/configs/nsh/defconfig) ? Options are:
```
CONFIG_SYSTEM_NXDIAG=y
CONFIG_SYSTEM_NXDIAG_COMP_FLAGS=y
CONFIG_SYSTEM_NXDIAG_CONF=y
CONFIG_SYSTEM_NXDIAG_ESPRESSIF=y
CONFIG_SYSTEM_NXDIAG_HOST_PATH=y
```
3) Lastly, could be please use [this PR](https://github.com/apache/nuttx/pull/11299) to test it and could you give us a feedback about PR(it solved or not)?
Thanks,

**Comment by dapeng0512** [comment]
Hi @eren-terzioglu 

Thank you for your reply.

1. I didn’t use pre-build version. because it couldn’t be started in my environment. It doesn’t seem to support this flash chip. The specific log is as follows:
![image](https://github.com/apache/nuttx/assets/15180245/3785e602-b36e-4ca4-932e-a6ebb242d01e)

2. As required, this is a complete log：
<img width="1042" alt="image" src="https://github.com/apache/nuttx/assets/15180245/76ad190c-1406-4771-8221-802c88b561bc">

3. Using this [PR](https://github.com/apache/nuttx/pull/11299) can solve the wifi crash problem, in my environment. Thank you very much.
