### ISSUE TITLE
[help] how to set CONFIG_DISABLE_IDLE_LOOP in defconfig

### ISSUE THREAD

**Issue by yf13** [apache/nuttx#11368]
I have  `CONFIG_DISABLE_IDLE_LOOP=y` added to my defconfig, but after running `tools/configure.sh`, the option is not in resulted `.config`. Thus I have to use `kconfig-tweak --enable DISABLE_IDLE_LOOP` to set it each time. 

How to correctly set  it in my defconfig so that it won't lost in `.config`?

**Comment by xiaoxiang781216** [comment]
You can't enable DISABLE_IDLE_LOOP from defconfig, since DISABLE_IDLE_LOOP is designed to be selected by other options in Kconfig, for examples SYSTEM_OFLOADER:
https://github.com/apache/nuttx-apps/blob/master/system/ofloader/Kconfig#L9

**Comment by xiaoxiang781216** [comment]
it's inside Linux kernel: https://www.kernel.org/doc/html/latest/kbuild/kconfig-language.html

**Comment by yf13** [comment]
I see. I was wondering there might be some differences.

**Comment by xiaoxiang781216** [comment]
No, NuttX' config is same as Linux.

**Comment by yf13** [comment]
I guess this [copy](https://bitbucket.org/nuttx/tools/src/master/kconfig-language.txt) it is. :)
