### ISSUE TITLE
cxxfilt was included in official NuttX documentation install but is not present on Ubuntu

### ISSUE THREAD

**Issue by acassis** [apache/nuttx#11376]
I receive a comment from a user trying to install NuttX dependencies and cannot figure out how to install cxxfilt because pip message recommends to run apt install python3-cxxfilt but this packet doesn't exist on Ubuntu.

More info:
https://www.embeddedrelated.com/showarticle/1524.php#comments

@xiaoxiang781216 any idea how to solve this issue?

**Comment by xiaoxiang781216** [comment]
I am using Ubuntu 22.04, the installation run without problem. @Gary-Hobson do you encounter the similar problem?

**Comment by Gary-Hobson** [comment]
I am using ubuntu 22.04, but I reproduced this problem in docker

I found the reason and solution on stackoverflow: https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana

The recommended solution is:
```
python3 -m venv .venv
source .venv/bin/activate
pip install cxxfilt
```
A simpler way is:
```
pip install --break-system-packages --user cxxfilt
```

**Comment by acassis** [comment]
Thank you @Gary-Hobson and @xiaoxiang781216
