### ISSUE TITLE
use SDCard on NuttX question。

### ISSUE THREAD

**Issue by GC-20-20** [apache/nuttx#11420]
I tried to follow the tutorial to use the SD card on the nuttx, but now it reports this error when mounting the SD:
<img width="190" alt="1702973112641" src="https://github.com/apache/nuttx/assets/78419332/7f8109b5-2450-4570-a9ca-436d6f7a396d">
I can't find what type of error this is.

**Comment by acassis** [comment]
@GC-20-20 Please share more information about your setup. What board are you using, what Ubuntu version, what toolchain, etc.

This number 5 means I/O Error, please look at nuttx/include/errno.h

**Comment by GC-20-20** [comment]
> @GC-20-20 Please share more information about your setup. What board are you using, what Ubuntu version, what toolchain, etc.请分享有关您的设置的更多信息。你用的是什么板子，什么Ubuntu版本，什么工具链，等等。
> 
> This number 5 means I/O Error, please look at nuttx/include/errno.h这个数字 5 表示 I/O 错误，请查看 nuttx/include/errno.h



> @GC-20-20 Please share more information about your setup. What board are you using, what Ubuntu version, what toolchain, etc.请分享有关您的设置的更多信息。你用的是什么板子，什么Ubuntu版本，什么工具链，等等。
> 
> This number 5 means I/O Error, please look at nuttx/include/errno.h这个数字 5 表示 I/O 错误，请查看 nuttx/include/errno.h

Thank you very much for your reply, I am using a Chinese learning development board with STM32F429, I rechecked the SDIO pins and the configuration information, but it still can't be mounted with ERROR: 5. Do you have any idea in this case?
![1703154120689](https://github.com/apache/nuttx/assets/78419332/70d1fe4b-f50c-4ed6-9cf9-8815717d7091)

**Comment by acassis** [comment]
@GC-20-20 please double check you board config, I suggest you to look the SDCARD examples for stm32f4discovery and stm32f401rc-rs485. Double checkout all pins and notice that your board doesn't have the Card Dection (CD) pin connected to the MCU. 

Also you can enable the debug options to collect more information:

```
Build Setup  --->
    Debug Options  --->
        [*] Enable Debug Features
        ...
        [*]   File System Debug Features
        [*]     File System Error Output
        [*]     File System Warnings Output
        ...
        [*]   Memory Card Driver Debug Features
        [*]     Memory Card Driver Error Output
        [*]     Memory Card Driver Warnings Output
        [*]     Memory Card Driver Informational Output
```

**Comment by GC-20-20** [comment]
@acassis Thanks for your reply, I have now successfully mounted it. The cause was a hardware problem, two modules were mounted on the SDIO bus, masking one of them worked.
