### ISSUE TITLE
ESP32S3:  LEDC does not have output. 

### ISSUE THREAD

**Issue by w2016561536** [apache/nuttx#11476]
## Problem:   
Use the examples of pwm in nuttx. Execute the command ` pwm ` in terminal. The output is  always LOW (GPIO 2, the default pin of channel 0). And I'm sure the hardware is OK because it can works in idf. More accurately, the GPIO2 is floating after reset, and connect to ground after execute the command.  

## Test conditions:    
Configs: ` esp32s3-devkit:pwm `,  no changes.  
Hardware: ESP32S3-WROOM-1(M0N4R2)  

## More tests: 
It seems that ` PWM Mutiple Outpur Channels Support ` does not open. So I open it and configure the examples of pwm channel to 0 and 1 (default is 1 and 2). Test again. Nothing changed, except GPIO 3 output low either.

**Comment by acassis** [comment]
Hi @w2016561536 thank you for reporting this issue, when I tested it last year everything was working fine. @tmedicci do you know if it stopped to work?

**Comment by tmedicci** [comment]
I'll take a look soon. I returned from my vacation today and there is a lot of stuff to get back to the routine. I'm sorry for that.

**Comment by w2016561536** [comment]
> I'll take a look soon. I returned from my vacation today and there is a lot of stuff to get back to the routine. I'm sorry for that.

I have found the problem of ledc does not have the output. I am trying to make it better to fit for a wider range of frequency. Thanks for your contributions!
