### ISSUE TITLE
FAT incorrect macro

### ISSUE THREAD

**Issue by resyfer** [apache/nuttx#11646]
In [this](https://github.com/apache/nuttx/blob/master/fs/fat/fs_fat32.h#L264), `DIRSEC_BYTENDX` takes in `f` and `i`, yet expansion only uses `i`.

Macro is used like `DIRSEC_BYTENDX(fs, idx)`, which needs to expand to have `DIRSEC_NDXMASK(fs)`, but due to the nature of the typo, it still works as intended as it uses `fs` right from the scope of the function instead when it expands.

**Comment by acassis** [comment]
Closed by https://github.com/apache/nuttx/pull/11647
