### ISSUE TITLE
Incident with Pull Requests and Actions

### ISSUE THREAD

**Issue by simbit18** [apache/nuttx#11819]
**GitHub Status**

https://www.githubstatus.com/

**Comment by simbit18** [comment]
Now github is ok. I think you need rebase or update from upstream/master

**Comment by acassis** [comment]
Thank you @simbit18, but seems it still failing :'(

@xiaoxiang781216 what do you think? Is it better stop merging the PRs until the CI be fixed again?

**Comment by xiaoxiang781216** [comment]
> Thank you @simbit18, but seems it still failing :'(
> 
> @xiaoxiang781216 what do you think? Is it better stop merging the PRs until the CI be fixed again?

Yes, but it's strange that https://github.com/apache/nuttx/pull/11676/checks pass all ci check.

**Comment by simbit18** [comment]
With the **old cibuild.sh**  #11826 the problem still remains.

In my test repository instead seems ok [[nuttx-testing-ci](https://github.com/simbit18/nuttx-testing-ci/actions/runs/8121359403)]
with branch [nuttx -> simbit18-test](https://github.com/simbit18/nuttx/commits/simbit18-test/) without https://github.com/apache/nuttx/pull/11202
