### ISSUE TITLE
OpenOCD: Fix stack alignment for cortex-m targets

### ISSUE THREAD

**Issue by acassis** [apache/nuttx#11955]
Hi @masayuki2009 since you submitted NuttX support on OpenOCD some years ago, could you please review/approve: https://review.openocd.org/c/openocd/+/8180 ?

**Comment by masayuki2009** [comment]
> Hi @masayuki2009 since you submitted NuttX support on OpenOCD some years ago, could you please review/approve: https://review.openocd.org/c/openocd/+/8180 ?

@acassis 
I added my comments to the gerrit.
