### ISSUE TITLE
TLSF usage issue on `rv-virt` target

### ISSUE THREAD

**Issue by yf13** [apache/nuttx#12209]
It seems that TLSF heap manager doesn't work well with `rv-virt` on Ubuntu 22.04.

## Reproduce:

- Used configurations: `rv-virt/knsh64`, `rv-virt/knsh32`, or `rv-virt/nsh64`
- Before building, do `kconfig-tweak -e MM_TLSF_MANAGER -d MM_DEFAULT_MANAGER` to enable TLSF manager.
- Build nuttx,
- Run nuttx with qemu 6,2 but can't see `NSH> ` prompt.

Please teach if the usage is incorrect.

**Comment by acassis** [comment]
@masayuki2009 @lupyuen did you see this issue?

**Comment by xiaoxiang781216** [comment]
this is due to compiler generate infinite recursion for ffs on RISCV, @Gary-Hobson will provide a patch fix it.

**Comment by Gary-Hobson** [comment]
@yf13 The fixed patch has been submitted  https://github.com/apache/nuttx/pull/12263

You can add the -s -S parameter after the qemu startup command to connect to gdb for debugging

```
qemu-system-riscv64 -semihosting -M virt,aclint=on -cpu rv64 -smp 8 -bios none -kernel nuttx -nographic -S -s
gdb-multiarch nuttx  -ex "target remote 127.0.0.1:1234"
```
