### ISSUE TITLE
How to support I2C slave device mode?

### ISSUE THREAD

**Issue by xiaotailang** [apache/nuttx#12518]
How can the system support I2C slave device mode? In the case where one STM32 board uses I2C0 as the master device and another STM32 board uses I2C1 as the slave device, they should be able to exchange data with each other. Alternatively, on the same board, if I2C0 acts as the master device and I2C1 operates as the slave device, they should also be capable of transmitting data between themselves.
I have located the i2c_slave.c file within the system, but I haven't found a concrete usage example. Are there any examples available for reference, specifically for scenarios where the master and slave devices send data to each other?

**Comment by acassis** [comment]
@xiaotailang I don't think STM32 port has support to I2C slave, I think it is only supported by:
arch/arm/src/s32k1xx/s32k1xx_lpi2c_slave.c
arch/arm/src/s32k3xx/s32k3xx_lpi2c.c
