### ISSUE TITLE
C++ constructors have too many priveleges (PROTECTED MODE)

### ISSUE THREAD

**Issue by patacongo** [apache/nuttx#1265]
C++ CONSTRUCTORS HAVE TOO MANY PRIVILEGES (PROTECTED MODE)

When a C++ ELF module is loaded, its C++ constructors are called via sched/task_starthook.c logic.  This logic runs in protected mode.  The is a security hole because the user code runs with kernel-privileges when the constructor executes.  Further, I suspect that the constructors also run with interrupts disabled.  That is just wrong.

Destructors likely have the opposite problem.  The probably try to execute some kernel logic in user mode?  Obviously this needs to be investigated further.

Related to Issue #1263

**Comment by xiaoxiang781216** [comment]
close, already fix.
