### ISSUE TITLE
[HELP] prompts  "undefined referenc to `_impure_prt`"

### ISSUE THREAD

**Issue by superxyxiao** [apache/nuttx#12907]
### Description

I have to use nuttx version 8.2. Using libm in newlibc, the link prompts an "undefined referenc to `_impure_prt`" error when using the lagmma function. How can I solve this? 

### Verification

- [x] I have verified before submitting the report.

**Comment by acassis** [comment]
@superxyxiao it seems something used by newlibc reentrancy, see: https://embdev.net/topic/what-is-_impure_ptr
lagmma is not part of NuttX libc yet

**Comment by xiaoxiang781216** [comment]
mainline already fix this problem: https://github.com/apache/nuttx/blob/master/libs/libc/misc/lib_impure.c
8.2 is very very old release, I would suggest you upgrade to the new release.

**Comment by superxyxiao** [comment]
Thank you very much.

When calling log2() in protected build mode, the User.map file does not have log2() symbols and cannot compile the elf file. But log2() works fine in app.bin, How can I solve this？

gcc version 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907] (GNU Tools for Arm Embedded Processors 7-2018-q2-update)

**Comment by xiaoxiang781216** [comment]
which libm library are use using?

**Comment by superxyxiao** [comment]
Using libm from newlib

**Comment by xiaoxiang781216** [comment]
do you add libm to the ld command line when you build user space bin?
