### ISSUE TITLE
[HELP] <How to add sifive uart support？>

### ISSUE THREAD

**Issue by yorange1** [apache/nuttx#13135]
### Description

Hello everyone，

I am trying to run Nuttx on a platform that uses sifive uart. OpenSBI prints information and completes the jump, but there is no output in Nuttx. I realize that there seems to be no driver support for sifive uart in Nuttx. How should I add this driver in Nuttx? Is there any guiding document here?

Thanks

### Verification

- [X] I have verified before submitting the report.

**Comment by anjiahao1** [comment]
`drivers/serial` add uart dirver in here

**Comment by anjiahao1** [comment]
`serial_cmsdk.c` is a arm cmsdk uart dirver, you can follow it add a sifive uart dirver.
