### ISSUE TITLE
[BUG] `make html` won't run when no board has been configured.

### ISSUE THREAD

**Issue by nonpawite** [apache/nuttx#13232]
### Description / Steps to reproduce the issue

When I ran `make html` to build a documentation preview, I received the following message.

```
NuttX has not been configured!
To configure the project:
  tools/configure.sh <config>
For a list of available configurations:
  tools/configure.sh -L
```

Isn't the `make html` command be independent and doesn't need the board to be configured?

### On which OS does this issue occur?

[Linux]

### What is the version of your OS?

Ubuntu 24.04.1

### NuttX Version

master

### Issue Architecture

[all]

### Issue Area

[Build System]

### Verification

- [X] I have verified before submitting the report.

**Comment by raiden00pl** [comment]
you have to call `make html` from `Documentation` direcotry
```
cd Documentation
make html
```
