### ISSUE TITLE
Help with Understanding Simulator Build Process

### ISSUE THREAD

**Issue by PwnVerse** [apache/nuttx#13304]
### Description

Hi, I'm trying to understand the build process of nuttx kernel using the configuration for `sim:posix_spawn`. I see that the `sim` architecture has a `nuttx-names.in` which the linker uses and likely creates the `nuttx-names.dat` during build process. The symbols I see in this file seem like the linker is trying to redirect some of them to host stdlib whenever available (ex - `pthread_sigmask` has a custom stdlib implementation at `sched/pthread_sigmask.c`) but the simulator uses host stdlib's `pthread_sigmask` (`pthread_sigmask@GLIBC_2.32`). 

There are some functions which get redirected to their custom implementations and some that get redirected towards host stdlib. My question is, when and how is this symbol redirection decided, specifically, how does the linker know which symbols to redirect to custom stdlib and which ones to redirect towards host stdlib?

### Verification

- [X] I have verified before submitting the report.

**Comment by acassis** [comment]
@PwnVerse as Greg pointed to Documentation at https://cwiki.apache.org/confluence/display/NUTTX/NuttX+Simulation
Could you please close this Issue?
