### ISSUE TITLE
Improve Github labels for NuttX

### ISSUE THREAD

**Issue by raiden00pl** [apache/nuttx#13522]
### Description

Currently, the labels are not very readable. There is too much colors for lables that don't really mean anything and there is no distinction on the type/context of label. 

Here are how it's organized in RIOT:

https://github.com/RIOT-OS/RIOT/labels

here for Zephyr:

https://github.com/zephyrproject-rtos/zephyr/labels

here for RT-Thread:

https://github.com/RT-Thread/rt-thread/labels

I would like to change it to be similar to the examples above:

1. add context for some labels like: "Platform: arm", "Area: Documentation", "Community: help wanted".
It would be ideal if each label had a context assigned, but I don't know if it's possible.
2. change the color of labels so that labels with the same context have the same color.
3.  see what labels are missing (for example, the size of the change)

Does anyone have any objections ? Personally, I like how it's done in RIOT. If you know of any other github projects that have this handled nicely, please link here.

If we have clear and readable labels, we can later automate labeling with https://github.com/actions/labeler and other tools

### Verification

- [X] I have verified before submitting the report.

**Comment by xiaoxiang781216** [comment]
all wokr is done, should we close this issue? @raiden00pl
