### ISSUE TITLE
[BUG] Build error with fs_pseudofile.c on master

### ISSUE THREAD

**Issue by adriendesp** [apache/nuttx#13756]
### Description / Steps to reproduce the issue

Where : In the file `fs/vfs/fs_pseudofile.c`, in method `pseudofile_munmap`, since #13443 
When : When `CONFIG_PSEUDOFS_FILE=y` is enabled
What : The following build error is returned : 

`libm/lib_nanl.c vfs/fs_pseudofile.c: In function 'pseudofile_munmap':
vfs/fs_pseudofile.c:367:7: error: 'ret' undeclared (first use in this function)
  367 |       ret = OK;
      |       ^~~`

Also, it seems that this return variable isn't really relevant in the way it is implemented.

### On which OS does this issue occur?

[OS: Linux]

### What is the version of your OS?

Ubuntu 22.04.3

### NuttX Version

master

### Issue Architecture

[Arch: arm]

### Issue Area

[Area: File System]

### Verification

- [X] I have verified before submitting the report.

**Comment by Donny9** [comment]
@adriendesp  hello, you can try with PR https://github.com/apache/nuttx/pull/13759.
