### ISSUE TITLE
[FEATURE] Enhance the CI Workflow to skip the Unmodified Architectures

### ISSUE THREAD

**Issue by lupyuen** [apache/nuttx#13775]
### Is your feature request related to a problem? Please describe.

- We're using too many GitHub Runners and Build Minutes, exceeding the [ASF Policy for GitHub Actions](https://infra.apache.org/github-actions-policy.html)
- NuttX Devs need to wait (2 hours) for the CI Build to complete across all Architectures (Arm32, Arm64, RISC-V, Xtensa), even though they're modifying a Single Architecture
- What if CI could build only the Modified Architecture?

### Describe the solution you'd like

- We propose a Partial Solution, based on the Arch Labels (recently added to CI)
- If "Arch: arm / arm64" is the only non-size label, then we build `other`, `arm-01`, `arm-02`, ...
- Similar rules for RISC-V and Xtensa
- We target only the Simplest PRs: One Arch Label + One Size Label, like "Arch: risc-v, Size: XS"

#### Fetch the Arch Labels

This is how we fetch the Arch Labels, and identify as Arm / Arm64, RISC-V, Xtensa. (Sorry I can't distinguish between Arm and Arm64, due to the Wildcard Matching)

https://github.com/lupyuen5/label-nuttx/blob/master/.github/workflows/build.yml#L134-L165

```yaml
      # Get the Arch for the PR: arm, arm64, risc-v, xtensa, ...
      - name: Get arch
        id: get-arch
        run: |
          # Get the Labels for the PR: "Arch: risc-v \n Size: XS"
          pr=${{github.event.pull_request.number}}
          if [[ "$pr" == "" ]]; then
            echo Not a PR, will build all targets
            exit
          fi
          numlabels=$(gh pr view $pr --repo $GITHUB_REPOSITORY --json labels --jq '.[] | length')
          labels=$(gh pr view $pr --repo $GITHUB_REPOSITORY --json labels --jq '.labels[] | .name')

          # Identify the Size and Arch Labels
          if [[ "$labels" == *"Size: "* ]]; then
            echo Labels contain size
            labels_contain_size=1
          fi
          if [[ "$labels" == *"Arch: arm"* ]]; then
            echo Arch contains arm or arm64
            arch_contains_arm_arm64=1
          fi
          if [[ "$labels" == *"Arch: risc-v"* ]]; then
            echo Arch contains risc-v
            arch_contains_riscv=1
          fi
          if [[ "$labels" == *"Arch: xtensa"* ]]; then
            echo Arch contains xtensa
            arch_contains_xtensa=1
          fi
```

#### For Arm Arch: Identify the Non-Arm Builds

Suppose the PR says "Arch: arm" or "Arch: arm64". We filter out the builds that should be skipped (RISC-V, Xtensa, etc):

https://github.com/lupyuen5/label-nuttx/blob/master/.github/workflows/build.yml#L165-L180

```yaml
          # We consider only PRs with 2 labels, including size
          if [ $numlabels -ne 2 ] || [ $labels_contain_size -ne 1 ]; then
            exit
          fi
          
          # If "Arch: arm / arm64" is the only non-size label, then build other, arm-01, arm-02, ...
          if [ $arch_contains_arm_arm64 -eq 1 ]; then
            if [[ "${{matrix.boards}}" == "arm"* ]] || [[ "${{matrix.boards}}" == "other"* ]]; then
              echo Allow build: ${{matrix.boards}}
            else
              echo Skip build: ${{matrix.boards}}
              echo "skip_build=1" >> $GITHUB_OUTPUT
            fi
          fi
```

#### Skip The Non-Arm Builds

Earlier we have identified the builds to be skipped. This is how we actually skip the builds:

https://github.com/lupyuen5/label-nuttx/blob/master/.github/workflows/build.yml#L236-L255

```yaml
      - name: Run builds
        #### Skip build if the arch is not modified
        if: ${{ steps.get-arch.outputs.skip_build != '1' }}
        uses: ./sources/nuttx/.github/actions/ci-container
        with:
          run: ## Omitted: Call cibuild.sh
```

#### Same for RISC-V and Xtensa Builds

We do the same for RISC-V and Xtensa:

https://github.com/lupyuen5/label-nuttx/blob/master/.github/workflows/build.yml#L180-L200

```yaml
          # If "Arch: risc-v" is the only non-size label, then build risc-v-01, risc-v-02
          if [ $arch_contains_riscv -eq 1 ]; then
            if [[ "${{matrix.boards}}" == "risc-v"* ]]; then
              echo Allow build: ${{matrix.boards}}
            else
              echo Skip build: ${{matrix.boards}}
              echo "skip_build=1" >> $GITHUB_OUTPUT
            fi
          fi

          # If "Arch: xtensa" is the only non-size label, then build xtensa-01, xtensa-02
          if [ $arch_contains_xtensa -eq 1 ]; then
            if [[ "${{matrix.boards}}" == "xtensa"* ]]; then
              echo Allow build: ${{matrix.boards}}
            else
              echo Skip build: ${{matrix.boards}}
              echo "skip_build=1" >> $GITHUB_OUTPUT
            fi
          fi
```

TODO: For these Simple PRs, shall we skip the `macos`, `macos/sim-*`, `msys2` builds? Since these builds are costly?

TODO: Should we have Board Labels by Arch also?

#### Testing

When we test our updated CI Workflow, we see that the irrelevant builds are skipped in seconds. Click "Show All Jobs" to reveal the timings:

- [CI Build for Arm32 PR](https://github.com/lupyuen5/label-nuttx/actions/runs/11126403047)

  (Completed in 2 hours 5 mins, roughly 10 mins faster than before. Bottleneck is `arm-05`, which takes 2 hours 5 mins, we should split into smaller jobs. Also we should probably exclude from Simple PRs the `macos` and `macos/sim-*` builds, which will take 2 hours to complete due to the queueing for macOS Runners)

- [CI Build for RISC-V PR](https://github.com/lupyuen5/label-nuttx/actions/runs/11126399134)

  (Completed in 2 hours. Bottleneck is `riscv-01` and `riscv-01`, at 1 hour 44 mins each, we should split into smaller jobs. Also we should probably exclude from Simple PRs the `macos` and `macos/sim-*` builds)

- [CI Build for Xtensa PR](https://github.com/lupyuen5/label-nuttx/actions/runs/11126640297)

  (Completed in 2 hours 16 mins. Bottleneck is `xtensa-01` and `xtensa-02`, at 1 hour 15 mins each. But most of the time is spent on the `macos` and `macos/sim-*` builds. We should probably exclude them from Simple PRs)

- [CI Build for Non-PR (All Targets)](https://github.com/lupyuen5/label-nuttx/actions/runs/11127664521)

  (Completed in 2 hours 34 mins. Same as the present CI)

- When PRs are Merged: All Targets are recompiled (2 hours 13 mins), no changes from the Present CI. [Merge Arm32 PR](https://github.com/lupyuen5/label-nuttx/actions/runs/11141175582)

Hi @raiden00pl and @simbit18: Do you think this will work? And keep Our Devs and ASF happy? Thanks!

### Verification

- [X] I have verified before submitting the report.

**Comment by simbit18** [comment]
Hi @lupyuen
Nice system to skip jobs!!!! :)

I think that a further margin of reduction of the generalized time of the jobs is possible with these simple solutions:
- use of an archive folder for packages repeated several times in the configurations present in the job (git and curl in the NuttX and NuttX-Apps repositories example in PR #13301 )
- addition of other configurations in the .dat files (testlist folder) with cmake + ninja to compile NuttX.

**Comment by lupyuen** [comment]
Thanks @simbit18! Your suggestions are excellent, I think we can implement them carefully after we have rolled out the solution above. I still have lots to learn about the Storage Folder and CMake :-)

**Comment by raiden00pl** [comment]
Great ! That's what I had in mind when creating new labels. 
The only problem I see is that I don't quite understand how github chooses the order of workflows in a parallel build. This approach will only work if the labeler is called before the build. Is this always ensured ?

> TODO: Should we have Board Labels by Arch also?

I think so. Another approach is to add "Platform" label which detect more precisely the arch used (like "Platform: STM32"), but then the problem of having too many labels may occur. Or we can add "Platform" labels for some of the most popular chips that are most frequently modified or they use CI the most.

**Comment by lupyuen** [comment]
> The only problem I see is that I don't quite understand how github chooses the order of workflows in a parallel build. This approach will only work if the labeler is called before the build. Is this always ensured ?

Thanks @raiden00pl! Yep I wonder about the order of workflows. If we look at a [Typical CI Run](https://github.com/apache/nuttx/pull/13805):

![Screenshot 2024-10-03 at 2 50 43 PM](https://github.com/user-attachments/assets/b169450e-b838-4fb8-b4f3-095512b22924)

- First thing that runs is `build.yml > Fetch-Source`, which will take [1 minute](https://github.com/apache/nuttx/actions/runs/11154914787)
- Then `labeler.yml > Labeler` starts concurrently to set the Labels
- Up next is `build.yml > Linux (arm-01)`. Which will start after `Fetch-Source`
- So we are OK (I think) as long as `Labeler` doesn't exceed 1 minute

We see some improvements: Arm32 builds now [complete in 2 hours](https://github.com/apache/nuttx/actions/runs/11154914787) (instead of 2 hours 15 mins). And we save on runners for RISC-V, Xtensa, Sim.

What's Next:
- I'll extend `build.yml` to handle `Arch: simulator` (as requested by Xiao Xiang)
- Skip `macos`, `macos/sim-*`, `msys2` for Simple PRs (1 Arch Label + 1 Size Label)
- Which will require the `Get Arch` logic to be refactored into a [Reusable Workflow](https://docs.github.com/en/actions/sharing-automations/reusing-workflows)
