### ISSUE TITLE
[HELP] Making HTTPS calls using MBEDTLS

### ISSUE THREAD

**Issue by engdavidiogo** [apache/nuttx#14010]
### Description

I need help understanding what is wrong with this implementation attempt.

I am trying to make **HTTPS** calls in my project using **MBEDTLS**, and for that, I am using the default **_Wi-Fi_** configuration for the **_ESP32C6_**.

`$ ./tools/configure.sh esp32c6-devkitc:wifi`

After that, I enable the following configurations in the menu:

**_CONFIG_CRYPTO_MBEDTLS_**
**_CONFIG_MBEDTLS_APPS_**
**_CONFIG_MBEDTLS_APP_BENCHMARK_**
**_CONFIG_MBEDTLS_APP_SELFTEST_**

With this configuration, when trying to build, I get the following output:

![image](https://github.com/user-attachments/assets/67fb3b2e-0b85-44e1-beaa-dcbcc12b80f8)

Please let me know if I skipped any necessary steps for success.

### Verification

- [X] I have verified before submitting the report.

**Comment by engdavidiogo** [comment]
Adding to what has already been said:

It seems like the issue is related to missing configurations in NuttX concerning the Espressif HAL for the ESP32C6.

As a validation, I enabled the MBEDTLS features using the following configuration for the STM32F746:

$ ./tools/configure.sh stm32f746g-disco:netnsh

![image](https://github.com/user-attachments/assets/60eec5e7-934d-4058-81b0-8f4ec77a1375)

I also applied the same configuration for the ESP32:

$ ./tools/configure.sh esp32-devkitc:wifi

![image](https://github.com/user-attachments/assets/06414081-4595-41ae-96b1-047ce8d01a7d)

@fdcavalcanti, @eren-terzioglu can you PTAL?

**Comment by fdcavalcanti** [comment]
Check`nuttx/arch/risc-v/src/esp32c6/esp-hal-3rdparty/nuttx/esp32c6/include/sdkconfig.h`.
You will see some symbols are already defined there, maybe it will help you better understand what's going on.

**Comment by pkarashchenko** [comment]
I was trying to deal with similar in the past in https://github.com/apache/nuttx/pull/11738
Seems like linking process is using `CFLAGS` with both app flags and flags from `Wireless.mk`

**Comment by FelipeMdeO** [comment]
You are right @pkarashchenko , I did same thing than you and now we are able to compile.
@fdcavalcanti  can you check whether a did right process here: https://github.com/espressif/esp-hal-3rdparty/pull/5, please?

**Comment by FelipeMdeO** [comment]
@engdavidiogo is everything ok in your side ?

**Comment by engdavidiogo** [comment]
Yes @FelipeMdeO , I can reproduce the build without any errors.

@fdcavalcanti  I continue testing and have no apparent problems

**Comment by FelipeMdeO** [comment]
@fdcavalcanti  We are able to update firmware using secure link, please lets update 3rdparty in nuttx master.

**Comment by tmedicci** [comment]
> Reference

We are testing the changes internally. As soon as our CI finishes, we can merge it. Thanks!

**Comment by tmedicci** [comment]
Hi @engdavidiogo and @FelipeMdeO ,

We merged it on `release/v5.1.c` branch:https://github.com/espressif/esp-hal-3rdparty/commit/26d4d1b57d54b63384b4e466b9e644ff0fe702b5

Can you please test it setting `ESP_HAL_3RDPARTY_VERSION=26d4d1b57d54b63384b4e466b9e644ff0fe702b5` before the `make` command to build NuttX? (we'd still need to update the hash for the HAL on NuttX)

**Comment by engdavidiogo** [comment]
Hi @tmedicci thanks for the support with this!

Closing...
