### ISSUE TITLE
[HELP] Boot multi-core on FVP A510, but the code still run "while (up_testset(lock) == SP_LOCKED)"  loop in spin_lock()

### ISSUE THREAD

**Issue by lzc1001** [apache/nuttx#14257]
### Description

Hi everyone!
I want to boot multi-core on FVP A510. After cpu1 run to WFI instruction, cpu0 run to "while (up_testset(lock) == SP_LOCKED)"  loop. This flow is: sched_unlock() (in nx_start()) -> nxsched_merge_pending() -> nxsched_add_readytorun() -> "DEBUGVERIFY(up_cpu_pause(cpu));" -> "spin_lock(&g_cpu_paused[cpu]);" -> spin_lock() -> "while (up_testset(lock) == SP_LOCKED)" in spin_lock(), then the code is still run in this loop. the input parameter "cpu" of up_cpu_pause() is 1 because of the task in “btcb” belong to cpu1 but the code run on cpu0 currently, and the cpu1 is in idle loop. So, it seem that cpu0 is waiting cpu1 to end its task but cpu1 task is still running. I don't know how to solve this issue and I don't konw the task scheduler how to work correctly in this case  
Thank you very much!
![image](https://github.com/user-attachments/assets/7dbf1680-ac36-40b6-9138-18736f02cc9c)
![image](https://github.com/user-attachments/assets/b0a45a2b-fb2a-4458-a413-fd0c0459db4b)
![image](https://github.com/user-attachments/assets/bd9daf2b-a1fe-4fac-bd6b-3bb71f8d3b84)
![image](https://github.com/user-attachments/assets/4646d48b-1dc0-47ac-8c92-179c700e3ffc)
![image](https://github.com/user-attachments/assets/aa509335-5190-4a69-bcb6-90eae1d5a6b2)

### Verification

- [X] I have verified before submitting the report.

**Comment by anchao** [comment]
@hujun260

**Comment by hujun260** [comment]
@lzc1001 
You are using an older version of the code. In the latest community implementation, the synchronous pause function has been removed. It is recommended that you synchronize with the latest community code and try again.

Based on the problem you described, the issue seems to be that CPU1 is unable to respond to interrupts.

**Comment by hujun260** [comment]
The old version can also run well,  but the new version will have significantly improved performance, especially in SMP.

**Comment by lzc1001** [comment]
@hujun260 @anchao OK! Thank you very much!
I solve this issues by define "CONFIG_ARCH_SET_VMPIDR_EL2" in configuration file. The GIC was initilized incorrectly because the value of MPIDR_EL1 is incorrect in EL1. And it would casue an incorret cpuid and initilized GIC redistributor incorrectly. So, When I set VMPIDR_EL2 in EL2, this isuse is solved, hhh✌

**Comment by lzc1001** [comment]
Hi, I have another question for function "int arm64_gic_send_sgi()". I find that read vaule of GICR_IGROUP0 is 0x0 in non-secure EL1, but the value is 0xDFFF00FF in secure and the value(0xDFFF00FF) is set by ARM TF-A in EL3. So, Is the "if " judgement condition reasonable when the core run in non-secure EL1?
![image](https://github.com/user-attachments/assets/df2ac52e-c1b4-4e9d-82d8-ec6af42638da)
Those two pictures are from Learn the architecture - Generic Interrupt Controller v3 and v4, Overview
![image](https://github.com/user-attachments/assets/ba391d17-c3a5-475d-9f5a-bf1620d9d8e1)
![image](https://github.com/user-attachments/assets/328e5867-0a60-4abe-855a-dd8f0bab9f56)

**Comment by hujun260** [comment]
There are modifications to arm64_gic_send_sgi in the latest code. Please check it out first.

**Comment by lzc1001** [comment]
@hujun260 I download the latest code(commit 204871513486e940fbb29a9a524de9b9e063d3e0 (HEAD -> master, origin/master, origin/HEAD)), but the function "arm64_gic_send_sgi" is same as my location code(commit 7a865b247969a9dbc06eddcaf58c59a14dd05d6d (HEAD -> releases/12.6, tag: nuttx-12.6.0-RC1, origin/releases/12.6)), I'm just curious about this issue. hhh
