### ISSUE TITLE
[HELP] SPI Slave Driver - semaphore release in spi_slave_read

### ISSUE THREAD

**Issue by FelipeMdeO** [apache/nuttx#14369]
### Description

Hello All,

I have other doubt about spi slave driver implementation, it is related spi_slave_driver.c file.

In current implementation we have semaphore reader:
```
  /* The semphore reader */

  sem_t wait;
```
It is used in `spi_slave.read` function, for instance:

```
 if (priv->rx_length == 0)
        {
          nxmutex_unlock(&priv->lock);
          if (filep->f_oflags & O_NONBLOCK)
            {
              return -EAGAIN;
            }

         ret = nxsem_wait(&priv->wait);
          if (ret < 0)
            {
              return ret;
            }

          ret = nxmutex_lock(&priv->lock);
          if (ret < 0)
            {
              spierr("Failed to get exclusive access: %d\n", ret);
              return ret;
            }
        }
    }
```

The same semaphore is handle in `spi_notify` function. But trying search call of this function across the entire project, I cannot find any call of `SPIS_DEV_NOTIFY`.

@Donny9 , Can you check my reasoning, please?

If so, can you give me an example of how you used the `SPIS_DEV_NOTIFY` function?

In the lower half I'm working on, I see the `SPIS_DEV_SELECT` function call inside the spi interrupt, but no reference to notify.

### Verification

- [X] I have verified before submitting the report.

**Comment by xiaoxiang781216** [comment]
@Donny9 please look at this issue.

**Comment by Donny9** [comment]
@FelipeMdeO please look PR https://github.com/apache/nuttx/pull/14411, you can add SPIS_DEV_NOTIFY in interrupt when rx or tx complete

**Comment by FelipeMdeO** [comment]
Thank you @Donny9 .
