### ISSUE TITLE
[BUG] debug log "lost" carrier return in master

### ISSUE THREAD

**Issue by FelipeMdeO** [apache/nuttx#14418]
### Description / Steps to reproduce the issue

Hello All,

Using realeases/12.7 I am able to see debug output properly:
![image](https://github.com/user-attachments/assets/941bb3ae-7f89-423f-953c-c6351b51c189)

But when I move to master branch I am losting carrier return after printfs:
![image](https://github.com/user-attachments/assets/312859cb-bd31-432d-88e7-b0f2a38d5a52)

I am using esp32c6-devkitc:spi config.

### On which OS does this issue occur?

[OS: Linux]

### What is the version of your OS?

Ubuntu 24.0

### NuttX Version

Master

### Issue Architecture

[Arch: all]

### Issue Area

[Area: Kernel]

### Verification

- [X] I have verified before submitting the report.

**Comment by xiaoxiang781216** [comment]
is the master or 12.7 branch?

**Comment by anchao** [comment]
Regression of https://github.com/apache/nuttx/pull/14362  ?

**Comment by yangsong8-ai** [comment]
Please try to set CONFIG_SYSLOG_CRLF=y
