### ISSUE TITLE
Inquiry about BLE support for BL602 in NuttX

### ISSUE THREAD

**Issue by FlyyingPiggy2020** [apache/nuttx#14424]
### Description

I'm currently working with the BL602 microcontroller and I’m interested in using NuttX for my project. I would like to know if NuttX has support for Bluetooth Low Energy (BLE) on the BL602 platform.

### Verification

- [X] I have verified before submitting the report.

**Comment by acassis** [comment]
@FlyyingPiggy2020 I suggest you to contact Bouffalo Lab, they added the initial support but didn´t contribute the complete support like Espressif did. So it is important they know there is customer willing to use their chips with NuttX to continue contributing
