### ISSUE TITLE
[HELP] How to get the more cpu status when NuttX is running

### ISSUE THREAD

**Issue by lzc1001** [apache/nuttx#14484]
### Description

Hi everyone, 
I have boot NuttX on FVP multi-core, and those cores are armv8a arch, but I don't know how to get the status of each core. 
I found "coredump" command in NuttX documentation, but I don't know how to use it on FVP. It seem that this command isn't support FVP
Thank you every much!

### Verification

- [X] I have verified before submitting the report.

**Comment by xiaoxiang781216** [comment]
which state do you want to get?

**Comment by lzc1001** [comment]
@xiaoxiang781216 I want to get each core ID by /proc/cpuinfo on FVP A510, But the related code isn't implemented for ARMV8A. I want get these information to verify multi-core are both active. I am also trying to write a simple multi-task code for verifing this.

**Comment by lzc1001** [comment]
@xiaoxiang781216 hhh, I have run apps/testing/smp_main.c to verify each core is activity. Thank you very much, I wonder if there's another way to check or prove this?😄

**Comment by xiaoxiang781216** [comment]
ps could also show multiple idle thread, and testing/cpuload could simulate the loading on the specific cpu core.

**Comment by lzc1001** [comment]
@xiaoxiang781216 Thank you very much!
