### ISSUE TITLE
[HELP] SPI Slave example stopped work after nuttx example changes

### ISSUE THREAD

**Issue by FelipeMdeO** [apache/nuttx#14639]
### Description

Hello All,

SPI Slave example stopped work after commit 761ee819568a52f1934ccf17bae20fe9816ebdec. @yamt  do you have any idea why its happen?

I am running in esp32c6 mcu, spi example can be found in: examples/spislv_test

### Verification

- [X] I have verified before submitting the report.

**Comment by acassis** [comment]
Guys we need real HW testing! We cannot break the system this way every time a new commit is submitted.

@tmedicci do you have SPI Slave implemented in your HW CI testing?

**Comment by eren-terzioglu** [comment]
Hi @acassis,
We don't have a hardware test for SPI Slave on CI.

**Comment by acassis** [comment]
Thank you @eren-terzioglu for confirming!
I think this could be a nice test to avoid regression like this

**Comment by FelipeMdeO** [comment]
Guys, If you want I can supply hardware (esp32c6 devkits) and remote machine to run a hardware test. Let me know if I can help in this improvement.

**Comment by FelipeMdeO** [comment]
Hello @yamt ,

Do have any idea why changes crashed spi slave feature ?
