### ISSUE TITLE
[BUG] seemingly wrong up_putc usage in lcd drivers

### ISSUE THREAD

**Issue by yamt** [apache/nuttx#14694]
### Description / Steps to reproduce the issue

many lcd drivers have a code fragment like the following:

https://github.com/apache/nuttx/blob/db31e569579c7ec9753d5fb69d07e8f997c7eae1/boards/arm/stm32/stm3240g-eval/src/stm32_lcd.c#L519-L539

(i'm not sure why it's common for lcd drivers. maybe just a result of heavy copy-and-paste?)

it seems like mixing syslog and up_putc, assuming they output to the same console.
of course, the assumption might or might not be correct, depending on the system and configurations.

this isn't a major problem as these code fragments are often wrapped with `#if 0` though.

### On which OS does this issue occur?

[OS: Mac]

### What is the version of your OS?

macOS 14.7

### NuttX Version

master

### Issue Architecture

[Arch: all]

### Issue Area

[Area: Drivers]

### Verification

- [X] I have verified before submitting the report.

**Comment by acassis** [comment]
@yamt good catch, according to git blame these lines were added by @patacongo in 2012 and 2014 respectively, so I think it is not my mistake, should have some reason.

**Comment by patacongo** [comment]
> @yamt good catch, according to git blame these lines were added by @patacongo in 2012 and 2014 respectively, so I think it is not my mistake, should have some reason.

Its just old debug code that was left in.  The xyz_dumprun() functions are not referenced from anywhere in the OS and just be removed.
