### ISSUE TITLE
[HELP] Documentation Update

### ISSUE THREAD

**Issue by trns1997** [apache/nuttx#14918]
### Description

I recently upgraded to Ubuntu 24.04 and i wanted to reinstall nuttx and its dependencies. I found a tiny issue. 
Here:
![Screenshot from 2024-11-24 11-16-20](https://github.com/user-attachments/assets/e0ec60cd-4eb1-47fa-a494-df5432779df2)
When i call `pip install kconfiglib` i get the following error:
```
➜  nuttx git:(master) ✗ pip install kconfiglib
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
``` 
They seemed to have gotten stricter on installing system wide python packages. The solution is simple i just installed the lib using the following command which is the recommended method:
```
sudo apt install python3-kconfiglib
```

Let me know if i should go ahead and create an MR for this doc update or it is not really worth it?

### Verification

- [X] I have verified before submitting the report.

**Comment by xiaoxiang781216** [comment]
Yes, please go ahead.
