### ISSUE TITLE
[HELP] TCP/IP psock_send_eventhandler hardfault

### ISSUE THREAD

**Issue by vladsomai** [apache/nuttx#15049]
### Description

Hello,

We are running NuttX 12.6 on a STM32H7 MCU and ran into an issue right after accepting a socket connection where the board crashed. The hardfault together with the addr2line output on each flash address is attached as a txt file.
[hardfault.txt](https://github.com/user-attachments/files/18009462/hardfault.txt)

I attached an image with the Wireshark trace.
![wireshark](https://github.com/user-attachments/assets/2d33d50e-9092-40c4-b858-82a422723bfa)

The IP 192.168.1.36 is running NuttX 12.6 release, while the IP 192.168.1.178 is running Windows 10.
According to the Wireshark data, both sides of the connection send a [PSH, ACK] message. The message going from 36 -> 178 waits for ACK with Seq=1, but the Windows machine sends a request instead of an ACK with Seq=1 causing the board to enter in hardfault.

Can someone help identify what could cause this issue and how to fix it?

### Verification

- [X] I have verified before submitting the report.

**Comment by acassis** [comment]
@wengzhe could you please take a look ^

**Comment by acassis** [comment]
@vladsomai did you test on 12.7.0 to confirm same issue still present?

**Comment by vladsomai** [comment]
@acassis we tested today on 12.7.0 and the issue is still present

**Comment by wengzhe** [comment]
Hi @vladsomai, I'm confused with the backtrace you posted: `/Nuttx/net/tcp/tcp_send_buffered.c:434`, which seems to be the first line of the function `psock_send_eventhandler` https://github.com/apache/nuttx/blob/releases/12.6/net/tcp/tcp_send_buffered.c#L434. Is your code same as the code on GitHub (which means you got the hardfault when your device just entered `psock_send_eventhandler`)?

**Comment by wengzhe** [comment]
Hi @vladsomai, we have found a similar issue that may crash in `psock_send_eventhandler`, but 
not at the beginning, so I'm not sure whether they're the same one, may you try this patch? https://github.com/apache/nuttx/pull/15287

**Comment by acassis** [comment]
@vladsomai please confirm that PR fixed the issue for you!

**Comment by vladsomai** [comment]
Sorry for comming back so late guys, we are having the holiday break and will not be able to test this until 8th of January. Thank you for looking into this.
