### ISSUE TITLE
[HELP] Nsh crash very easily if I call ls in command line

### ISSUE THREAD

**Issue by geniusdo** [apache/nuttx#15190]
### Description

I ported nuttx on my stm32h743vi board with usb cdc console configured. Its very likely to crash if I call ls command in nsh but other command wouldn't cause the issue. And i tried to use serial console, it worked fine. Very weird. I am pretty new to nuttx. I wonder how do I find where the problem is.  Any help or suggestion would be appreciated.

### Verification

- [X] I have verified before submitting the report.

**Comment by acassis** [comment]
Hi @geniusdo try to increase the Stack Size, for boards with USB normally you will need a bigger stack

**Comment by geniusdo** [comment]
Problem solved! Thanks for your help!
