### ISSUE TITLE
Do we still need IFF_DOWN?

### ISSUE THREAD

**Issue by masayuki2009** [apache/nuttx#1838]
I noticed that IFF_DOWN is used both in nuttx and in apps to control network interface.
In my understanding, IFF_UP is enough and IFF_DOWN is rather redundant.

So my question is that do we still need IFF_DOWN?

**Comment by xiaoxiang781216** [comment]
Same question for me, should we remove one? or change the coe from:
```
#define IFF_DOWN           (1 << 0) /* Interface is down */
#define IFF_UP             (1 << 1) /* Interface is up */
```
to:
```
#define IFF_DOWN           (0 << 1) /* Interface is down */
#define IFF_UP             (1 << 1) /* Interface is up */
```

**Comment by masayuki2009** [comment]
> Same question for me, should we remove one? or change the code from:
> 
> ```
> #define IFF_DOWN           (1 << 0) /* Interface is down */
> #define IFF_UP             (1 << 1) /* Interface is up */
> ```
> 
> to:
> 
> ```
> #define IFF_DOWN           (0 << 1) /* Interface is down */
> #define IFF_UP             (1 << 1) /* Interface is up */
> ```

@xiaoxiang781216 

I think that the above change does not work.
So I think we should replace all IFF_DOWN related code both in nuttx and in apps with IFF_UP.
