### ISSUE TITLE
CAN Bus driver will not exit.

### ISSUE THREAD

**Issue by davids5** [apache/nuttx#3927]
If the CAN bus connector is not connected to the bus. The queued writes can fill the SW FIFO and HW FIFO. The device will not close and will be hung here: https://github.com/apache/incubator-nuttx/blob/master/drivers/can/can.c#L532-L542

I would like feedback on some possible solutions.

1) Remove the code. - While it attempts an orderly shut down it will hang.
2) Allow the loops to try once to flush. Then time out and force the close resetting the HW and SW FIFO
3) Add IOCTLs akin to: 
      TCIFLUSH (CANIOC_IFLUSH) - flushes data received but not read.
      TCOFLUSH (CANIOC_OFLUSH)) - flushes data written but not transmitted.
      TCIOFLUSH (CANIOC_IOFLUSH) -flushes both data received but not read, and data written but not transmitted.
      FIONWRITE (CANIOC_FIONWRITE) - Number bytes in send queue (FIFO)

The last solution would allow the application to decide if it should linger on close.

**Comment by Igor-Misic** [comment]
Any progress with this issue?
