### ISSUE TITLE
SO_LINGER 0 does not drop the connection.

### ISSUE THREAD

**Issue by fjpanag** [apache/nuttx#7522]
When the option `SO_LINGER` is used with a timeout of 0, `close()` shall drop the TCP connection  immediately.

A TCP `RST` shall be sent, and all pending data shall be discarded.

This is not happening now: 
* TCP `RST` is not sent, rather the normal `FIN` disconnect procedure is followed.  
* The code **blocks indefinitely within `close()`**.

**Comment by xiaoxiang781216** [comment]
@anchao should we correct SO_LINGER?
