### ISSUE TITLE
An error occurred building maix-bit:nsh

### ISSUE THREAD

**Issue by GooTal** [apache/nuttx#7795]
With `nuttx` and `apps` both in **master** branch(commit id `af2b4914208cad676d64823f5e0bf08871617d80`) , i built nuttx image using command:
```
./tools/configure.sh -l maix-bit:nsh
make 
```
And an error occurred:
![图片](https://user-images.githubusercontent.com/40800103/205841735-8faf0b76-c978-4dbf-be7c-219c7cd3abbb.png)

I checkout to releases/11.0 branch and built image with the same command. No error occurred.

I\`m not quite familiar with nuttx. Any idea how to fix this? Thanks.

**Comment by xiaoxiang781216** [comment]
could you try this version:
https://github.com/apache/nuttx/blob/master/tools/ci/docker/linux/Dockerfile#L180

**Comment by GooTal** [comment]
Thanks, I\`ll try this later. 
But it seems that riscv cross cross compile tools is not the root cause. The branch `release/11.0` can be successfully built using riscv64-unknown-elf-gcc (12.1.0 on my ubuntu 22.04).

**Comment by xiaoxiang781216** [comment]
But maix-bit/nsh pass the daily ci https://github.com/apache/nuttx/actions/runs/3622886642/jobs/6108177030:
```
====================================================================================
Configuration/Tool: maix-bit/nsh
------------------------------------------------------------------------------------
  Cleaning...
  Configuring...
  Building NuttX...
  Normalize maix-bit/nsh
```
So, it should the environment difference.

**Comment by xiaoxiang781216** [comment]
Look like it's better to update the toolchain used by ci to the last version and fix the compiler issue.

**Comment by xiaoxiang781216** [comment]
Let's close this issue if you have more comment, please reopen again.
