### ISSUE TITLE
how can I enable shm_open and shm_unlink support?

### ISSUE THREAD

**Issue by linux-hacker** [apache/nuttx#7811]
Hello，

I want to use function shm_open and function shm_unlink. The files fs/shm/shm_open.c and fs/shm/shm_close.c in kernel implement these functions. However, these two source files were not found under the fs/shm/ path.

**Comment by xiaoxiang781216** [comment]
It isn't implemented yet:(. Maybe you can provide one:).

**Comment by jlaitine** [comment]
We have had implementation for this for some time, but only recently got it cleaned up. Now there is a PR for upstream as well:

https://github.com/apache/nuttx/pull/8109
