### ISSUE TITLE
SocketCAN broken since #7616

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [apache/nuttx#7812]
Since the changes from PR #7616 it seems that SocketCAN support is borken.

When transmitting a can frame using cansend it will keep sending the message indefinitely, it seems that `priv->dev.d_len` stays != 0.

Reading a frame using candump returns `read: incomplete CAN frame`  it seems that `recvmsg()` returns 0 bytes.

**Comment by xiaoxiang781216** [comment]
@anchao could you take a look?

**Comment by PetervdPerk-NXP** [comment]
I've found the workaround to the transmit problem it seems with new IOB api we've to explicitely set d_len to 0. Not sure about the other drivers that are affected by this.

```patch
diff --git a/arch/arm/src/s32k3xx/s32k3xx_flexcan.c b/arch/arm/src/s32k3xx/s32k3xx_flexcan.c
index 3e17b52ee0..d0ac32894d 100644
--- a/arch/arm/src/s32k3xx/s32k3xx_flexcan.c
+++ b/arch/arm/src/s32k3xx/s32k3xx_flexcan.c
@@ -905,6 +905,8 @@ static int s32k3xx_transmit(struct s32k3xx_driver_s *priv)

   mb->cs = cs; /* Go. */

+  priv->dev.d_len = 0;
+
   regval = getreg32(priv->base + S32K3XX_CAN_IMASK1_OFFSET);
   regval |= mb_bit;
   putreg32(regval, priv->base + S32K3XX_CAN_IMASK1_OFFSET);
```

**Comment by anchao** [comment]
> I've found the workaround to the transmit problem it seems with new IOB api we've to explicitely set d_len to 0. Not sure about the other drivers that are affected by this.

It seems to be the same issue as https://github.com/apache/nuttx/issues/7802 / https://github.com/apache/nuttx/pull/7807, I think d_len should be set to 0 after device callback,  I will submit a patch to resolve this issue from the common code

**Comment by anchao** [comment]
@PetervdPerk-NXP  I resubmit the https://github.com/apache/nuttx/pull/7807, please try this change if it can resolves your issue

**Comment by acassis** [comment]
@PetervdPerk-NXP could you please confirm it is working now and please close this issue

**Comment by xiaoxiang781216** [comment]
@acassis @PetervdPerk-NXP reply in #7807. It work, so let's close it.
