### ISSUE TITLE
undefined reference to `arm_serialinit'

### ISSUE THREAD

**Issue by develc** [apache/nuttx#7856]
I am trying to build for the RP2040, but I get this error:
<pre>
develc@localhost:~/source/nuttx/nuttx$ make -j1
make[1]: Entering directory '/home/develc/source/nuttx/apps'
make[2]: Entering directory '/home/develc/source/nuttx/apps/builtin'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/builtin'
make[2]: Entering directory '/home/develc/source/nuttx/apps/examples/hello'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/examples/hello'
make[2]: Entering directory '/home/develc/source/nuttx/apps/fsutils/mkfatfs'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/fsutils/mkfatfs'
make[2]: Entering directory '/home/develc/source/nuttx/apps/fsutils/mksmartfs'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/fsutils/mksmartfs'
make[2]: Entering directory '/home/develc/source/nuttx/apps/interpreters/lua'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/interpreters/lua'
make[2]: Entering directory '/home/develc/source/nuttx/apps/interpreters/minibasic'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/interpreters/minibasic'
make[2]: Entering directory '/home/develc/source/nuttx/apps/nshlib'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/nshlib'
make[2]: Entering directory '/home/develc/source/nuttx/apps/platform'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/platform'
make[2]: Entering directory '/home/develc/source/nuttx/apps/system/cle'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/system/cle'
make[2]: Entering directory '/home/develc/source/nuttx/apps/system/hexed'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/system/hexed'
make[2]: Entering directory '/home/develc/source/nuttx/apps/system/nsh'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/system/nsh'
make[2]: Entering directory '/home/develc/source/nuttx/apps/system/ramtest'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/system/ramtest'
make[2]: Entering directory '/home/develc/source/nuttx/apps/system/readline'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/system/readline'
make[2]: Entering directory '/home/develc/source/nuttx/apps/system/system'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/system/system'
make[2]: Entering directory '/home/develc/source/nuttx/apps/testing/getprime'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/testing/getprime'
make[2]: Entering directory '/home/develc/source/nuttx/apps/testing/ostest'
make[2]: Nothing to be done for 'depend'.
make[2]: Leaving directory '/home/develc/source/nuttx/apps/testing/ostest'
make[1]: Leaving directory '/home/develc/source/nuttx/apps'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/sched'
make[1]: Nothing to be done for 'depend'.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/sched'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/drivers'
make[1]: Nothing to be done for 'depend'.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/drivers'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/boards'
make[1]: Nothing to be done for 'depend'.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/boards'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/arch/arm/src'
make[1]: Nothing to be done for 'depend'.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/arch/arm/src'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/fs'
make[1]: Nothing to be done for 'depend'.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/fs'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/binfmt'
make[1]: Nothing to be done for 'depend'.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/binfmt'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/libs/libc'
make[1]: Nothing to be done for 'depend'.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/libs/libc'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/mm'
make[1]: Nothing to be done for 'depend'.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/mm'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/sched'
make[1]: 'libsched.a' is up to date.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/sched'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/drivers'
make[1]: 'libdrivers.a' is up to date.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/drivers'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/boards'
make[1]: 'libboards.a' is up to date.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/boards'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/libs/libc'
make[1]: 'libc.a' is up to date.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/libs/libc'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/mm'
make[1]: 'libmm.a' is up to date.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/mm'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/arch/arm/src'
make[1]: 'libarch.a' is up to date.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/arch/arm/src'
make[1]: Entering directory '/home/develc/source/nuttx/apps'
rm -f /home/develc/source/nuttx/apps/libapps.a
make /home/develc/source/nuttx/apps/libapps.a
make[2]: Entering directory '/home/develc/source/nuttx/apps'
make[3]: Entering directory '/home/develc/source/nuttx/apps/builtin'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/builtin'
make[3]: Entering directory '/home/develc/source/nuttx/apps/examples/hello'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/examples/hello'
make[3]: Entering directory '/home/develc/source/nuttx/apps/fsutils/mkfatfs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/fsutils/mkfatfs'
make[3]: Entering directory '/home/develc/source/nuttx/apps/fsutils/mksmartfs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/fsutils/mksmartfs'
make[3]: Entering directory '/home/develc/source/nuttx/apps/interpreters/lua'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/interpreters/lua'
make[3]: Entering directory '/home/develc/source/nuttx/apps/interpreters/minibasic'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/interpreters/minibasic'
make[3]: Entering directory '/home/develc/source/nuttx/apps/nshlib'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/nshlib'
make[3]: Entering directory '/home/develc/source/nuttx/apps/platform'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/platform'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/cle'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/cle'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/hexed'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/hexed'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/nsh'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/nsh'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/ramtest'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/ramtest'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/readline'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/readline'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/system'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/system'
make[3]: Entering directory '/home/develc/source/nuttx/apps/testing/getprime'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/testing/getprime'
make[3]: Entering directory '/home/develc/source/nuttx/apps/testing/ostest'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/home/develc/source/nuttx/apps/testing/ostest'
make[3]: Entering directory '/home/develc/source/nuttx/apps/builtin'
AR (add): libapps.a    builtin_list.c.home.develc.source.nuttx.apps.builtin.o exec_builtin.c.home.develc.source.nuttx.apps.builtin.o       
make[3]: Leaving directory '/home/develc/source/nuttx/apps/builtin'
make[3]: Entering directory '/home/develc/source/nuttx/apps/examples/hello'
AR (add): libapps.a        hello_main.c.home.develc.source.nuttx.apps.examples.hello.o   
make[3]: Leaving directory '/home/develc/source/nuttx/apps/examples/hello'
make[3]: Entering directory '/home/develc/source/nuttx/apps/fsutils/mkfatfs'
AR (add): libapps.a    mkfatfs.c.home.develc.source.nuttx.apps.fsutils.mkfatfs.o configfat.c.home.develc.source.nuttx.apps.fsutils.mkfatfs.o writefat.c.home.develc.source.nuttx.apps.fsutils.mkfatfs.o       
make[3]: Leaving directory '/home/develc/source/nuttx/apps/fsutils/mkfatfs'
make[3]: Entering directory '/home/develc/source/nuttx/apps/fsutils/mksmartfs'
AR (add): libapps.a    mksmartfs.c.home.develc.source.nuttx.apps.fsutils.mksmartfs.o       
make[3]: Leaving directory '/home/develc/source/nuttx/apps/fsutils/mksmartfs'
make[3]: Entering directory '/home/develc/source/nuttx/apps/interpreters/lua'
AR (add): libapps.a    lua-5.4.0/src/lapi.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lauxlib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lcode.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lctype.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/ldebug.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/ldo.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/ldump.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lfunc.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lgc.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/llex.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lmem.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lobject.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lopcodes.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lparser.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lstate.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lstring.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/ltable.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/ltm.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lundump.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lvm.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lzio.c.home.develc.source.nuttx.apps.interpreters.lua.o nuttx_linit.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lbaselib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lcorolib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/ldblib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/liolib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lmathlib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/loadlib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/loslib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lstrlib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/ltablib.c.home.develc.source.nuttx.apps.interpreters.lua.o lua-5.4.0/src/lutf8lib.c.home.develc.source.nuttx.apps.interpreters.lua.o    lua-5.4.0/src/lua.c.home.develc.source.nuttx.apps.interpreters.lua.o   
make[3]: Leaving directory '/home/develc/source/nuttx/apps/interpreters/lua'
make[3]: Entering directory '/home/develc/source/nuttx/apps/interpreters/minibasic'
AR (add): libapps.a    basic.c.home.develc.source.nuttx.apps.interpreters.minibasic.o    script.c.home.develc.source.nuttx.apps.interpreters.minibasic.o   
make[3]: Leaving directory '/home/develc/source/nuttx/apps/interpreters/minibasic'
make[3]: Entering directory '/home/develc/source/nuttx/apps/nshlib'
AR (add): libapps.a    nsh_init.c.home.develc.source.nuttx.apps.nshlib.o nsh_parse.c.home.develc.source.nuttx.apps.nshlib.o nsh_console.c.home.develc.source.nuttx.apps.nshlib.o nsh_script.c.home.develc.source.nuttx.apps.nshlib.o nsh_system.c.home.develc.source.nuttx.apps.nshlib.o nsh_command.c.home.develc.source.nuttx.apps.nshlib.o nsh_fscmds.c.home.develc.source.nuttx.apps.nshlib.o nsh_ddcmd.c.home.develc.source.nuttx.apps.nshlib.o nsh_proccmds.c.home.develc.source.nuttx.apps.nshlib.o nsh_mmcmds.c.home.develc.source.nuttx.apps.nshlib.o nsh_timcmds.c.home.develc.source.nuttx.apps.nshlib.o nsh_envcmds.c.home.develc.source.nuttx.apps.nshlib.o nsh_syscmds.c.home.develc.source.nuttx.apps.nshlib.o nsh_dbgcmds.c.home.develc.source.nuttx.apps.nshlib.o nsh_session.c.home.develc.source.nuttx.apps.nshlib.o nsh_login.c.home.develc.source.nuttx.apps.nshlib.o nsh_fsutils.c.home.develc.source.nuttx.apps.nshlib.o nsh_builtin.c.home.develc.source.nuttx.apps.nshlib.o nsh_mntcmds.c.home.develc.source.nuttx.apps.nshlib.o nsh_modcmds.c.home.develc.source.nuttx.apps.nshlib.o nsh_consolemain.c.home.develc.source.nuttx.apps.nshlib.o nsh_printf.c.home.develc.source.nuttx.apps.nshlib.o nsh_test.c.home.develc.source.nuttx.apps.nshlib.o nsh_usbconsole.c.home.develc.source.nuttx.apps.nshlib.o       
make[3]: Leaving directory '/home/develc/source/nuttx/apps/nshlib'
make[3]: Entering directory '/home/develc/source/nuttx/apps/platform'
AR (add): libapps.a    dummy.c.home.develc.source.nuttx.apps.platform.o       
make[3]: Leaving directory '/home/develc/source/nuttx/apps/platform'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/cle'
AR (add): libapps.a    cle.c.home.develc.source.nuttx.apps.system.cle.o       
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/cle'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/hexed'
AR (add): libapps.a    bfile.c.home.develc.source.nuttx.apps.system.hexed.o cmdargs.c.home.develc.source.nuttx.apps.system.hexed.o hexcopy.c.home.develc.source.nuttx.apps.system.hexed.o hexdump.c.home.develc.source.nuttx.apps.system.hexed.o hexenter.c.home.develc.source.nuttx.apps.system.hexed.o hexhelp.c.home.develc.source.nuttx.apps.system.hexed.o hexinsert.c.home.develc.source.nuttx.apps.system.hexed.o hexmove.c.home.develc.source.nuttx.apps.system.hexed.o hexremove.c.home.develc.source.nuttx.apps.system.hexed.o hexword.c.home.develc.source.nuttx.apps.system.hexed.o    hexed.c.home.develc.source.nuttx.apps.system.hexed.o   
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/hexed'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/nsh'
AR (add): libapps.a        nsh_main.c.home.develc.source.nuttx.apps.system.nsh.o sh_main.c.home.develc.source.nuttx.apps.system.nsh.o   
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/nsh'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/ramtest'
AR (add): libapps.a        ramtest.c.home.develc.source.nuttx.apps.system.ramtest.o   
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/ramtest'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/readline'
AR (add): libapps.a    readline.c.home.develc.source.nuttx.apps.system.readline.o readline_fd.c.home.develc.source.nuttx.apps.system.readline.o readline_common.c.home.develc.source.nuttx.apps.system.readline.o       
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/readline'
make[3]: Entering directory '/home/develc/source/nuttx/apps/system/system'
AR (add): libapps.a    system.c.home.develc.source.nuttx.apps.system.system.o       
make[3]: Leaving directory '/home/develc/source/nuttx/apps/system/system'
make[3]: Entering directory '/home/develc/source/nuttx/apps/testing/getprime'
AR (add): libapps.a        getprime_main.c.home.develc.source.nuttx.apps.testing.getprime.o   
make[3]: Leaving directory '/home/develc/source/nuttx/apps/testing/getprime'
make[3]: Entering directory '/home/develc/source/nuttx/apps/testing/ostest'
AR (add): libapps.a    getopt.c.home.develc.source.nuttx.apps.testing.ostest.o dev_null.c.home.develc.source.nuttx.apps.testing.ostest.o restart.c.home.develc.source.nuttx.apps.testing.ostest.o sigprocmask.c.home.develc.source.nuttx.apps.testing.ostest.o sighand.c.home.develc.source.nuttx.apps.testing.ostest.o signest.c.home.develc.source.nuttx.apps.testing.ostest.o setvbuf.c.home.develc.source.nuttx.apps.testing.ostest.o tls.c.home.develc.source.nuttx.apps.testing.ostest.o waitpid.c.home.develc.source.nuttx.apps.testing.ostest.o cancel.c.home.develc.source.nuttx.apps.testing.ostest.o cond.c.home.develc.source.nuttx.apps.testing.ostest.o mutex.c.home.develc.source.nuttx.apps.testing.ostest.o timedmutex.c.home.develc.source.nuttx.apps.testing.ostest.o sem.c.home.develc.source.nuttx.apps.testing.ostest.o semtimed.c.home.develc.source.nuttx.apps.testing.ostest.o barrier.c.home.develc.source.nuttx.apps.testing.ostest.o timedwait.c.home.develc.source.nuttx.apps.testing.ostest.o pthread_rwlock.c.home.develc.source.nuttx.apps.testing.ostest.o pthread_rwlock_cancel.c.home.develc.source.nuttx.apps.testing.ostest.o specific.c.home.develc.source.nuttx.apps.testing.ostest.o robust.c.home.develc.source.nuttx.apps.testing.ostest.o roundrobin.c.home.develc.source.nuttx.apps.testing.ostest.o mqueue.c.home.develc.source.nuttx.apps.testing.ostest.o timedmqueue.c.home.develc.source.nuttx.apps.testing.ostest.o vfork.c.home.develc.source.nuttx.apps.testing.ostest.o setjmp.c.home.develc.source.nuttx.apps.testing.ostest.o    ostest_main.c.home.develc.source.nuttx.apps.testing.ostest.o   
make[3]: Leaving directory '/home/develc/source/nuttx/apps/testing/ostest'
make[2]: Leaving directory '/home/develc/source/nuttx/apps'
make[1]: Leaving directory '/home/develc/source/nuttx/apps'
IN: /home/develc/source/nuttx/apps/libapps.a -> staging/libapps.a
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/fs'
make[1]: 'libfs.a' is up to date.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/fs'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/binfmt'
make[1]: 'libbinfmt.a' is up to date.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/binfmt'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/boards/arm/rp2040/common'
make[1]: 'libboard.a' is up to date.
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/boards/arm/rp2040/common'
make[1]: Entering directory '/home/develc/source/nuttx/nuttx/arch/arm/src'
make[2]: Entering directory '/home/develc/source/nuttx/nuttx/boards/arm/rp2040/common'
make[2]: 'libboard.a' is up to date.
make[2]: Leaving directory '/home/develc/source/nuttx/nuttx/boards/arm/rp2040/common'
LD: nuttx
arm-none-eabi-ld: /home/develc/source/nuttx/nuttx/staging/libarch.a(rp2040_start.o): in function `__start':
/home/develc/source/nuttx/nuttx/arch/arm/src/chip/rp2040_start.c:148: undefined reference to `arm_earlyserialinit'
arm-none-eabi-ld: /home/develc/source/nuttx/nuttx/staging/libarch.a(arm_initialize.o): in function `up_initialize':
/home/develc/source/nuttx/nuttx/arch/arm/src/common/arm_initialize.c:134: undefined reference to `arm_serialinit'
make[1]: *** [Makefile:174: nuttx] Error 1
make[1]: Leaving directory '/home/develc/source/nuttx/nuttx/arch/arm/src'
make: *** [tools/Unix.mk:516: nuttx] Error 2
develc@localhost:~/source/nuttx/nuttx$ _
</pre>

**Comment by nimish** [comment]
This happens if no uart is enabled. Enable UART0 and it'll pull in the right files.
