### ISSUE TITLE
token "@" is not valid in preprocessor expressions build failure with ARM GNU toolchain 11.3

### ISSUE THREAD

**Issue by mogenson** [apache/nuttx#8208]
I updated my ARM GCC toolchain from 10.3 to 11.3 and noticed a build failure.

```
misc/lib_impure.c:48:8: error: token "@" is not valid in preprocessor expressions
   48 | #  if (__NEWLIB__ < 4 || __NEWLIB__ == 4 && __NEWLIB_MINOR__ < 2)
      |        ^~~~~~~~~~
make[1]: *** [Makefile:135: bin//lib_impure.o] Error 1
make[1]: Leaving directory '/Users/mike/Code/nuttx-workspace/nuttx/libs/libc'
make: *** [tools/LibTargets.mk:174: libs/libc/libc.a] Error 2
```

This is with the NuttX 12.0 release. The 10.3 toolchain builds fine.

New: `arm-none-eabi-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712`
Old: `arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)`

**Comment by xiaoxiang781216** [comment]
This is the toolchain bug please apply this patch to your toolchain:
https://github.com/apache/nuttx/blob/master/tools/ci/patch/arm-none-eabi-workaround-for-newlib-version-break.patch

**Comment by mogenson** [comment]
Thanks, looks like I can close this issue.
