### ISSUE TITLE
UART4 & UART5 missing from stm32f103r_pinmap.h

### ISSUE THREAD

**Issue by dirksavage88** [apache/nuttx#8218]
The higher density stm32f103Rx chips (such as the stm32f103ret6) have UART4 & UART5. These UARTS are missing from the following pinmap:

https://github.com/apache/nuttx/blob/fac10b6ebdec6d98f8b833137153ec43e71d706d/arch/arm/src/stm32/hardware/stm32f103r_pinmap.h#L271

Adding the following lines would fix this issue:

```
#define GPIO_UART4_RX       (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN11)
#define GPIO_UART4_TX       (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHz|GPIO_PORTC|GPIO_PIN10)

#define GPIO_UART5_RX       (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN2)
#define GPIO_UART5_TX       (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHz|GPIO_PORTC|GPIO_PIN12)
```

However I am not sure if this would cause a breaking change on the lower density chips that do not have these UARTS.

**Comment by TimJTi** [comment]
Easy I think?

#if defined(ARCH_CHIP_STMxxx) || defined(ARCH_CHIP_STMyyy || etc
#  define GPIO_UART4_RX
etc
#endif

From: Andrew Brahim ***@***.***>
Date: Sunday, 22 January 2023 at 19:26
To: apache/nuttx ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [apache/nuttx] UART4 & UART5 missing from stm32f103r_pinmap.h (Issue #8218)

The higher density stm32f103Rx chips (such as the stm32f103ret6) have UART4 & UART5. These UARTS are missing from the following pinmap:

https://github.com/apache/nuttx/blob/fac10b6ebdec6d98f8b833137153ec43e71d706d/arch/arm/src/stm32/hardware/stm32f103r_pinmap.h#L271

Adding the following lines would fix this issue:

#define GPIO_UART4_RX       (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTC|GPIO_PIN11)

#define GPIO_UART4_TX       (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHz|GPIO_PORTC|GPIO_PIN10)



#define GPIO_UART5_RX       (GPIO_INPUT|GPIO_CNF_INFLOAT|GPIO_MODE_INPUT|GPIO_PORTD|GPIO_PIN2)

#define GPIO_UART5_TX       (GPIO_ALT|GPIO_CNF_AFPP|GPIO_MODE_50MHz|GPIO_PORTC|GPIO_PIN12)

However I am not sure if this would cause a breaking change on the lower density chips that do not have these UARTS.
