### ISSUE TITLE
Sending packet via SocketCAN

### ISSUE THREAD

**Issue by dvosahlik** [apache/nuttx#8290]
The can_sendmsg.c was modified in the commit 0cbbbb92153283f2727dbd2c0077443c7cdda85d

After the modification the dev->d_len is not anymore being set to the length of the can frame. Therefore, the send will not happen through the devif_poll. I suggest to add `dev->d_len = dev->d_sndlen;` to the can_sendmsg.c on the line 110, just after the call to `devif_send`

**Comment by xiaoxiang781216** [comment]
Could you send a PR?

**Comment by dvosahlik** [comment]
Sure, I will do that.
