### ISSUE TITLE
Replace all strcpy with strlcpy. But some boards has rom built-in strcpy, what should we do?

### ISSUE THREAD

**Issue by XinStellaris** [apache/nuttx#8450]
We want to improve code safety by replacing all strcpy with strlcpy.

During the replacement, I noticed that esp32c3, esp32s2, esp32, esp32s3 use rom strcpy.
nuttx/boards/risc-v/esp32c3/common/scripts/esp32c3_rom.ld:1944:strcpy = 0x40000364;
nuttx/boards/xtensa/esp32s2/common/scripts/esp32s2_rom.ld:836:PROVIDE ( strcpy = 0x40007cfc );
nuttx/boards/xtensa/esp32/common/scripts/esp32_rom.ld:1822:PROVIDE ( strcpy = 0x400013ac );
nuttx/boards/xtensa/esp32s3/common/scripts/esp32s3_rom.ld:2426:PROVIDE ( strcpy = 0x40001218 );

What should we do about these boards? Should we tell esp group to  implement strlcpy in rom? Or just use common strlcpy implementation with CONFIG_LIBC_ARCH_STRLCPY=false?

**Comment by acassis** [comment]
@XinStellaris there is already strlcpy in ROM:
```
esp32/common/scripts/esp32_rom.ld:PROVIDE ( strlcpy = 0x4000c584 );
esp32s2/common/scripts/esp32s2_rom.ld:PROVIDE ( strlcpy = 0x4001adf8 );
esp32s3/common/scripts/esp32s3_rom.ld:PROVIDE ( strlcpy = 0x400013bc );
```
I think it is just missing for esp32c3

**Comment by XinStellaris** [comment]
I just noticed there is a strlcpy for esp32c3:
nuttx/boards/risc-v/esp32c3/common/scripts/esp32c3_rom.ld:1944:strcpy = 0x40000364;

So nothing is missing,  this issue is just a mistake.
I will close this issue.
