### ISSUE TITLE
what is virtual resolution?

### ISSUE THREAD

**Issue by gneworld** [apache/nuttx#8607]
![47VyNWsHO4](https://user-images.githubusercontent.com/30924021/220315104-cceeb7c6-cfd9-4b47-9d6e-db8180547aa4.jpg)
what does the meaning of xres_virtual and yres_virtual? In what scenarios is it used?
                                                                                                                                                                  thanks much

**Comment by xiaoxiang781216** [comment]
it comes from: https://github.com/torvalds/linux/blob/master/include/uapi/linux/fb.h#L242-L248
it's used to support the double frame buffer with FBIOPAN_DISPLAY ioctl:
https://github.com/torvalds/linux/blob/master/include/uapi/linux/fb.h#L19

**Comment by xiaoxiang781216** [comment]
Here is the PR with more context info: https://github.com/apache/nuttx/pull/4632

**Comment by gneworld** [comment]
thanks very much!

**Comment by gneworld** [comment]
If the system has only one frame buffer for displaying，in other words, NOT SUPPORT FBIOPAN_DISPLAY,  then how to avoid or 
 mitigate the screen tearing problems?

**Comment by xiaoxiang781216** [comment]
In this case, you have to control the timing very precisely:

1. Notify the graphic stack immediately after you finish DMA buffer to panel
2. The graphic stack must finish the rendering before the next vsync start

If you panel has a framebuffer internally, you may switch the command mode, the item 2 could be relaxed. For item 1, you can reference PR: https://github.com/apache/nuttx/pull/7783.

**Comment by gneworld** [comment]
many thanks~~
