### ISSUE TITLE
filep of #6708

### ISSUE THREAD

**Issue by exteriorform** [apache/nuttx#8720]
Hi NuttXer:
    I was puzzed by #6708, where there's an additional function parameter `struct file *filep` was added but it was not used in function at all, does it means the `filep` will be used in future?

**Comment by xiaoxiang781216** [comment]
it's used here:
https://github.com/apache/nuttx/blob/master/drivers/sensors/sensor_rpmsg.c#L568-L608

**Comment by exteriorform** [comment]
got it！thanks for your explanation.
