### ISSUE TITLE
does nsh support ++,+= operation?

### ISSUE THREAD

**Issue by gneworld** [apache/nuttx#8810]
test it in sim, report  command not found
![image](https://user-images.githubusercontent.com/30924021/224868887-ee271072-2680-463a-922f-c6c243715f52.png)

**Comment by gneworld** [comment]
![image](https://user-images.githubusercontent.com/30924021/224868865-59a073f7-1b78-4a08-88d5-d9d34e77e309.png)

**Comment by xiaoxiang781216** [comment]
nsh doens't implement the shell expression yet, the contribution is welcome.:)
