### ISSUE TITLE
solved

### ISSUE THREAD

**Issue by gneworld** [apache/nuttx#8815]
solved

**Comment by acassis** [comment]
@gneworld good finding! Probably you found an issue in NuttX MD5 algo.
I tested MD5 on NuttX using ESP32 internet MD5 hardware calculator and it worked: https://acassis.wordpress.com/2022/11/08/testing-hmac-md5-on-esp32/

But I didn't test it using NuttX MD5, if I had tested it probably should find this issue that you found! :-)

**Comment by fjpanag** [comment]
I just did some quick tests of the md5 algorithm.

I checked NuttX's md5 against our "own" implementation which is known to be correct and agrees 100% with the Linux algorithm for the last several years.

For all files provided to the algorithms, the results were identical.  
I believe there is nothing wrong with NuttX MD5.

---

However. MD5 is **crucial** to be correct.  
In embedded systems is used extensively to validate OTA received files, firmware updates etc.

I would like someone else to repeat the test.  
Or maybe, such algorithms should have unit tests in CI?

Shall we re-open this issue, till it is verified correct?

@acassis what do you think? Can you help with a test of NuttX vs ESP32 MD5?
