### ISSUE TITLE
Issues with adjtime implementation / Build failure.

### ISSUE THREAD

**Issue by patacongo** [apache/nuttx#8858]
adjtime() is the semi-standard method used in NuttX, Linux, and FreeBSD to gradually adapt the system time so that it is in agreement with RTC time.  It differs from clock_synchronize() or clock_resynchronize() in that it is intended to be used during normal runtime without disrupting ongoing timing operations rather than at exceptional times like power up or wake-up from sleep.

adjtime() is implemented in sched/clock/clock_timekeeping.  A quick review reveals several problems:

1. **Missing system call**.  The implemented of adjtime() is provided, but there is no call gate implemented in syscall/ and include/sys _[NOT a problem.  See comment below]_.

3. **Adjustment has limited range**.  The logic calculates a separate adjustment that is added to the current time (a timespec).  The  adjustment value is a type long with an LSB of 1 nonosecond.  So the total range is only +/-2 seconds (assuming that long is 32-bits).  That is an insufficient range for systems that are always on.

This is because adjtime() does not follow the man page:  "If the adjustment in delta is positive, then the system clock is  speeded up by some small percentage (i.e., by adding a small  amount of time to the clock value in each second) until the  adjustment has been completed.  If the adjustment in delta is negative, then the clock is slowed down in a similar fashion."

If small adjustments were added to a full timespec or if the clock rate is modified instead, overflow would not occur.

3. Notice that the man page quote above does not talk about adjustments to the time, but rather about adjustments to the rate of the clock (speeded up or slowed down.  Hmmm..  There is no such word as speeded up, is there?  Isn't the past tense of speed sped, not speeded.)

5. **No guarantee of monotonically increasing time**.  The requirement is:  "The adjustment that adjtime() makes to the clock is carried out   in such a manner that the clock is always monotonically  increasing."  But I see nothing that guarantees this.  If adjtime() were implemented correctly so that the clock rate is adjusted, not the current time, then that would meet this requirement.

If the rate of the clock source is set even just a little too fast, it would be impossible to both adjust the time downward and to also guarantee a strictly monotonically increasing time.  The only way to accomplish that would be to adjust the clock rate downward.

Forward time steps should also be small.  The corrections are suppose to work gradually over time.

If system time were to "go backward" that could result in threads locking up waiting under certain circumstances.: Calculated time delays would be enormous.

Reference:  https://man7.org/linux/man-pages/man3/adjtime.3.html (Linux) and https://man.freebsd.org/cgi/man.cgi?query=adjtime&sektion=2&n=1 (FreeBSD)

6. **Build Failure.**  If I try building a configuration with CONFIG_CLOCK_TIMEKEEPING enabled, the build fails with the error:  

    clock/clock_initialize.c:340:35  error 'g_basetime' undeclared (first use in this function): ...

This is because g_basetime is conditionally compiled out when CONFIG_CLOCK_TIMEKEEPING is enabled.  However the following commit added references to g_basetime that are not guarded by CONFIG_CLOCK_TIMEKEEPING:

    46bd8798c55 sched/clock/clock_initialize.c (Xiang Xiao      2018-11-12 06:50:37 -0600 371)       rtc_diff->tv_sec  = rtc_time.tv_sec  - curr_ts.tv_sec;
    46bd8798c55 sched/clock/clock_initialize.c (Xiang Xiao      2018-11-12 06:50:37 -0600 372)       rtc_diff->tv_nsec = rtc_time.tv_nsec - curr_ts.tv_nsec;

    commit 46bd8798c551c2fb5f26d57559214c02e8946637
    Author: Xiang Xiao <xiaoxiang@xiaomi.com>
    Date:   Mon Nov 12 06:50:37 2018 -0600

        sched/clock/:  Remove g_monotonic_basetime and g_clock_monotonic_time since we don't need ensure monotonic time start from zero as state here: http://pubs.opengroup.org/onlinepubs/009696899/functions/clock_getres.html

To replicate this failure:

  a. make distclean
  b. tools/configure.sh stm3240g-eval:nsh
  c. make menuconfig (enable CONFIG_CLOCK_TIMEKEEPING)
  d. make

**Comment by cederom** [comment]
Here are some references :-)

https://github.com/freebsd/freebsd-src/blob/master/contrib/ntp/libntp/adjtime.c

https://github.com/freebsd/freebsd-src/blob/master/contrib/ntp/include/ntp_syscall.h

https://github.com/freebsd/freebsd-src/blob/main/sys/kern/kern_time.c

And the man page :-)

https://man.freebsd.org/cgi/man.cgi?query=adjtime&sektion=2&apropos=0&manpath=FreeBSD+13.1-RELEASE+and+Ports

     The adjtime() system call makes small adjustments to the system time, as
     returned by gettimeofday(2), advancing or retarding it by the time    speci-
     fied by the timeval delta.     If delta is negative, the clock is slowed
     down by incrementing it more slowly than normal until the correction is
     complete.    If delta is positive, a    larger increment than normal is    used.
     The skew used to perform the correction is    generally a fraction of    one
     percent.  Thus, the time is always    a monotonically    increasing function.
     A time correction from an earlier call to adjtime() may not be finished
     when adjtime() is called again.  If olddelta is not a null    pointer, the
     structure pointed to will contain,    upon return, the number    of microsec-
     onds still    to be corrected    from the earlier call.

     This call may be used by time servers that    synchronize the    clocks of com-
     puters in a local area network.  Such time    servers    would slow down    the
     clocks of some machines and speed up the clocks of    others to bring    them
     to    the average network time.

     The adjtime() system call is restricted to    the super-user.


Hope that helps :-)

**Comment by michallenc** [comment]
Thank you Greg @patacongo  for detailed issue description. I agree clock rate adjustment would be better solution and would solve possible problems with time jumps. This is also how time synchronization is handled in RTEMS implementation of adjtime() function.

I will take a look into possible implementation to NuttX mainline.

**Comment by patacongo** [comment]
> I will take a look into possible implementation to NuttX mainline.

There are lots of implementations of algorithms out there, so fixing the NuttX adjtime should not be too difficult (although it doesn't even compiler now if you enable TIMEKEEPING).

It will require special architecture-specific hooks to modify the clock rate, but these can be conditioned on CONFIG_HAVE_CLOCK_TIMEKEEPING as the logic is now, so it does not require modification of all architectures.

**Comment by michallenc** [comment]
> adjtime() does depend on the architecture-specific code providing interfaces to adjust the clock rate, so perhaps it would need to depend on CONFIG_ARCH_HAVE_TIMEKEEPING

@patacongo That is the current state. I just changed it that adjtime() would depend on CONFIG_ARCH_HAVE_ADJTIME and CONFIG_CLOCK_ADJTIME. Mostly because current timekeeping implementation does not use traditional basetime structure

```
#ifndef CONFIG_CLOCK_TIMEKEEPING
struct timespec   g_basetime;
#endif
```

As can be seen here https://github.com/apache/nuttx/blob/master/sched/clock/clock_initialize.c#L58. Therefore there is a different aproach for settime and gettime. I think maybe we should keep the implementation of adjtime (under CONFIG_CLOCK_ADJTIME) and other timekeeping function (wall time etc. under CONFIG_CLOCK_TIMEKEEPING) separately. This way it will be possible to use adjtime just for clock period adjustment when required by the user.
