### ISSUE TITLE
Enabling sinfo printing and disabling CONFIG_SYSLOG_TIMESTAMP_REALTIME caused a recursive calling bug?

### ISSUE THREAD

**Issue by GooTal** [apache/nuttx#8959]
I enabled sinfo printing:
![图片](https://user-images.githubusercontent.com/40800103/229732968-65422dbe-1ae7-4bd5-a722-ff7e2e28a15a.png)

I found that sinfo called nx_vsyslog, then called clock_gettime
```
  if (OSINIT_HW_READY())
    {
#if defined(CONFIG_SYSLOG_TIMESTAMP_REALTIME)
      /* Use CLOCK_REALTIME if so configured */

      clock_gettime(CLOCK_REALTIME, &ts);

#else
      /* Prefer monotonic when enabled, as it can be synchronized to
       * RTC with clock_resynchronize.
       */

      clock_gettime(CLOCK_MONOTONIC, &ts);
#endif
```
But clock_gettime called sinfo again, which makes a recursive bug?

Here`s the backtrace from gdb:

![图片](https://user-images.githubusercontent.com/40800103/229732230-965566fe-7e83-40b5-8e43-9cca54ec4fe3.png)

**Comment by anchao** [comment]
@GooTal already fixed by https://github.com/apache/nuttx/pull/8897

**Comment by GooTal** [comment]
@anchao Thanks a lot
