### ISSUE TITLE
Code does not rebuild properly after 'make menuconfig'

### ISSUE THREAD

**Issue by pkarashchenko** [apache/nuttx#8960]
Initially observed during testing of https://github.com/apache/nuttx/pull/8951
Steps to reproduce:
1. `tools/configure.sh spresense:smp`
2. `make menuconfig` -> set `CONFIG_PRIORITY_INHERITANCE=y`
3. `make -j8`
4. `make menuconfig` -> set `CONFIG_SEM_PREALLOCHOLDERS=0`
5. `make -j8`
6. Run binary on the board and observe crash on system startup
7. `make clean`
8. `make -j8`
9. Run binary on the board successfully without crash

Comparing `.map` files generated after step 5 and after step 8 shows that there is a difference in code segment size for multiple sections. This mean that code was not rebuilt with a proper configuration after configuration was changed with `make menuconfig`.

**Comment by davids5** [comment]
Was this closed because after changes to .config a clean build is required?

**Comment by pkarashchenko** [comment]
Yes. This behaviour seems to be "as expected". Most of the code is rebuilt because of `#include <nuttx/config.h>` and `config.h` is regenerated after `make menuconfig` exits, but there are some files that do not include it directly, so stale objects are used.

**Comment by davids5** [comment]
Given this, should make menuconfig run clean?

**Comment by pkarashchenko** [comment]
Yeah, that sounds reasonable.

**Comment by pkarashchenko** [comment]
Let me re-open an issue, so we can implement it
