### ISSUE TITLE
CAN RX packet data overwritten if NET_TIMESTAMP is used

### ISSUE THREAD

**Issue by haitomatic** [apache/nuttx#9108]
SocketCAN RX was working before https://github.com/apache/nuttx/pull/7616 . After I rebased to the latest Nuttx upstream then user application couldn't receive correct RX packet with `recvmsg` https://github.com/apache/nuttx/blob/master/net/socket/recvmsg.c

After sometimes troubleshooting, I found that since `CONFIG_NET_TIMESTAMP` was enabled in my system, the timestamp data actually overwrites the RX packet data in iob data buffer.
https://github.com/apache/nuttx/blob/93a1adf83e157b55f203b5a641419bb51af68a59/net/can/can_callback.c#L151

I was able to get the correct data then with the fix
`              len = iob_trycopyin(dev->d_iob, (FAR uint8_t *)&tv,
                                  sizeof(struct timeval), dev->d_iob->io_pktlen, false);
                                  `
@anchao @PetervdPerk-NXP can you guys take a look? Thank you!

**Comment by haitomatic** [comment]
yes, I assume so.

**Comment by haitomatic** [comment]
Hi, just tested and it worked. Thank you!

**Comment by anchao** [comment]
Hi @haitomatic , please ensure that the length of CONFIG_NET_LL_GUARDSIZE is equal to sizeof(struct timeval) (16).

**Comment by haitomatic** [comment]
yes, I checked that
```
./.config:CONFIG_NET_LL_GUARDSIZE=16
```
btw, 
```
              len = iob_trycopyin(dev->d_iob, (FAR uint8_t *)&tv,
                                  sizeof(struct timeval),
                                  -CONFIG_NET_LL_GUARDSIZE, false);
```
but offset is unsigned int  so that would mean offset will become 0?

**Comment by haitomatic** [comment]
oh, sorry, my nuttx is not latest with the changes in `mm/iob` . I will update it now and check again

**Comment by haitomatic** [comment]
alright, just made the update. tested again and it works now! Thanks!
