### ISSUE TITLE
Add MPU60X0 device driver to TIVA TM4C bring up sequence

### ISSUE THREAD

**Issue by fdcavalcanti** [apache/nuttx#9168]
Hi everyone,

I saw that the bring up sequence of the Nucleo-144 already registers the MPU60X0 device driver, if requested. So far, i've edited the bring up file on the TM4C board to bind the MPU driver on bring up and it works fine.

I would be happy to open this PR. However I have some questions:
Is there a standard way of executing this device driver binding?
Are there restrictions on the I2C bus? I see many board using the I2C1 only and I'm using I2C0.

Thanks

**Comment by ldube** [comment]
What i2c restrictions? I used  I2C0 in a tm4c board a few weeks ago.

[https://github.com/apache/nuttx/blob/1be95c3313059d31da3607987ce6135faa296dea/boards/arm/tiva/tm4c1294-launchpad/src/tm4c_bringup.c#L353](url)

Did I misread? Pushing code with your question is more efficient. This project can't keep up with issues as it is, so I would just close this issue and open a PR if I were you.
