### ISSUE TITLE
mcp2515 Spi bus configuration 

### ISSUE THREAD

**Issue by paolovolpi** [apache/nuttx#9391]
Spi bus configuration  should be done every time the bus is locked or different incompatible devices can't sit on the same bus. I saw it is pretty common to initialize the bus in nuttx drivers init functions, there is any good reason for that?

https://github.com/apache/nuttx/blob/6f87bcc9aca036d7d94f19b1b7c92f212c44cfb7/drivers/can/mcp2515.c#L2503-L2506

**Comment by acassis** [comment]
Yes, that is good point! You are right! Another patch? :-)
