### ISSUE TITLE
Changing configuration via 'make menuconfig' does not work sometimes on MACOS

### ISSUE THREAD

**Issue by pkarashchenko** [apache/nuttx#9670]
Steps to reproduce:
1. `./tools/configure.sh sim:citest`
2. `make menuconfig` -> select `CONFIG_LIBCXXABI=y` -> Save & Exit
3. `make -j8` ->
```
Create version.h
sed: 1: "/CONFIG_BASE_DEFCONFIG/ ...": bad flag in substitute command: '}'
make: *** [include/nuttx/config.h] Error 1
make: *** Waiting for unfinished jobs....
```

Another example:
1. `./tools/configure.sh sim:ostest`
2. `make menuconfig` -> select `CONFIG_STDIO_DISABLE_BUFFERING=y` -> Save & Exit
3. `make -j8` ->
```
Create version.h
sed: 1: "/CONFIG_BASE_DEFCONFIG/ ...": bad flag in substitute command: '}'
make: *** [include/nuttx/config.h] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by pkarashchenko** [comment]
Seems to be regression after https://github.com/apache/nuttx/commit/bc4266fa485

**Comment by pkarashchenko** [comment]
@lucasssvaz could you please take a look?

**Comment by acassis** [comment]
@lucasssvaz please take a look!

**Comment by lucasssvaz** [comment]
Just came back from vacation, sorry for all the trouble.
I messed up the differences between Linux and OSX sed's. You can't omit the semicolon on OSX, that's why the error occurs.
@pkarashchenko I currently don't have an OSX machine to test. Could you please check if #9754 now works as expected ?

**Comment by pkarashchenko** [comment]
Ok. Let me check

**Comment by pkarashchenko** [comment]
@lucasssvaz seems to be working fine.
