### ISSUE TITLE
how to use systemview

### ISSUE THREAD

**Issue by laoniaokkk** [apache/nuttx#9991]
I tried to use sysytemview to reference the sim/segger configuration, but I didn't succeed, and the issue on systemview was also unsuccessful. I would like to know how to go about setting it up to use correctly.

**Comment by acassis** [comment]
@xiaoxiang781216 I think we need a concise Documentation like we have to Debug Trace

**Comment by laoniaokkk** [comment]
> Please reference this link: #5843

I checked this issue but my issue is not solved, my NUTTX system version is 12.0.0 and my chip is stm32f429. I made sure the program executed up_perf_init() and opened DWT inside. When I click "Start Recording", SystemView doesn't show anything, then click "Stop Recording" to display as below. Can you give me your profile?

![SystemView](https://github.com/apache/nuttx/assets/104182270/d3d1ee47-d31c-4b86-a603-42e783deedbe)

**Comment by xiaoxiang781216** [comment]
@Gary-Hobson could you share some defconfig?

**Comment by raiden00pl** [comment]
@laoniaokkk you can try this PR https://github.com/apache/nuttx/pull/10006 
There is an example systemview configuration for nucleo-f446re.
The main problem I encountered with enabling systemview is `CONFIG_DRIVERS_NOTERAM=y` which is the default option and at the same time `CONFIG_DRIVERS_NOTE_MAX=1`. This cause systemview support to fail and no error is reported to the user.

**Comment by laoniaokkk** [comment]
> @laoniaokkk you can try this PR #10006 There is an example systemview configuration for nucleo-f446re. The main problem I encountered with enabling systemview is `CONFIG_DRIVERS_NOTERAM=y` which is the default option and at the same time `CONFIG_DRIVERS_NOTE_MAX=1`. This causes systemview support to fail and no error is reported to the user.

Yes,I made `CONFIG_DRIVERS_NOTE_MAX=2`, and then the SystemView was work well
